patches-version = "latest"
# cli-version = "dev"
enable-module-update = true

[moviebox-morphe]
enabled = true
pkg-name = "com.community.oneroom"
app-name = "moviebox"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "rushiranpise/morphe-patches"
patches-version = "dev"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://com-community-oneroom.en.uptodown.com/android"
# apkmirror-dlurl = ""
# dpi = "nodpi anydpi auto"
# archive-dlurl = ""
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.community.oneroom"









