# patches-version = "dev"
# cli-version = "dev"
enable-module-update = true

[gboard-morphe]
enabled = true
app-name = "gboard"
rv-brand = "morphe"
build-mode = "both"
arch = "arm64-v8a"
patches-source = "jasonwu1994/Gboard-patches"
excluded-patches = "'Package Rename'"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://gboard-go.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard"
dpi = "nodpi anydpi auto"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.inputmethod.latin"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.google.android.inputmethod.latin"

[gboard-morphe-clone]
enabled = true
app-name = "gboard"
rv-brand = "morphe-clone"
build-mode = "apk"
arch = "arm64-v8a"
patches-source = "jasonwu1994/Gboard-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://gboard-go.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard"
dpi = "nodpi anydpi auto"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.inputmethod.latin"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.google.android.inputmethod.latin"

[gboard-morphe-adobo]
enabled = true
app-name = "gboard"
rv-brand = "morphe-adobo"
build-mode = "both"
arch = "both"
patches-source = "jkennethcarino/adobo"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://gboard-go.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard"
dpi = "nodpi anydpi auto"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.inputmethod.latin"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.google.android.inputmethod.latin"



