name: "🐞 Builder issue"
description: "Report a bug or an issue related to the builder."
title: "builder issue: [Short Description]"
labels: ["builder"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction steps
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      options:
        - label: I have searched the existing issues and believe that this is not a duplicate.
          required: true
        - label: This bug is not related to ReVanced, Morphe or any other patch.
          required: true
