enable-module-update = true
patches-version = "absolutelatest"

[youtube-morphe-anddea]
enabled = true
app-name = "youtube"
rv-brand = "morphe-anddea"
build-mode = "both"
arch = "all"
pkg-name = "com.google.android.youtube"
cli-source = "MorpheApp/morphe-desktop"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/black --continue-on-error"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
dpi = "nodpi anydpi auto"
#archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.google.android.youtube"
patches-source = "anddea/revanced-patches"

[youtube-music-morphe-anddea]
enabled = true
app-name = "youtube-music"
rv-brand = "morphe-anddea"
build-mode = "both"
arch = "both64"
pkg-name = "com.google.android.apps.youtube.music"
cli-source = "MorpheApp/morphe-desktop"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/black --continue-on-error"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.google.android.apps.youtube.music"
patches-source = "anddea/revanced-patches"
