enable-module-update = true
patches-version = "absolutelatest"

[speedtest-morphe-xtra]
enabled = true
app-name = "speedtest"
pkg-name = "org.zwanoo.android.speedtest"
rv-brand = "morphe-xtra"
cache_repo_dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/org.zwanoo.android.speedtest"
build-mode = "apk"
arch = ["arm64-v8a", "arm-v7a"]
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://speedtest-net-mobile.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/ookla/speedtest"
dpi = ["nodpi", "anydpi", "auto"]
patches-source = "BholeyKaBhakt/revanced-patches-xtra"

[speedtest-morphe-xtra-exp]
enabled = true
app-name = "speedtest"
pkg-name = "org.zwanoo.android.speedtest"
rv-brand = "morphe-xtra-exp"
cache_repo_dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/org.zwanoo.android.speedtest"
version = "latest"
build-mode = "apk"
arch = ["arm64-v8a", "arm-v7a"]
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://speedtest-net-mobile.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/ookla/speedtest"
dpi = ["nodpi", "anydpi", "auto"]
patches-source = "BholeyKaBhakt/revanced-patches-xtra"

# ── Inshorts ──────────────────────────────────────────────────────────────────
[inshorts-morphe-xtra]
enabled = true
app-name = "inshorts"
rv-brand = "morphe-xtra"
pkg-name = "com.nis.app"
build-mode = "apk"
arch = ["all"]
cli-source = "MorpheApp/morphe-desktop"
cache_repo_dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.nis.app"
uptodown-dlurl = "https://inshorts.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/inshorts-formerly-news-in-shorts/inshorts-news-in-60-words-2"
dpi = ["nodpi", "anydpi", "auto"]
patches-source = "BholeyKaBhakt/revanced-patches-xtra"

[inshorts-morphe-xtra-exp]
enabled = true
app-name = "inshorts"
rv-brand = "morphe-xtra-exp"
pkg-name = "com.nis.app"
build-mode = "apk"
version = "latest"
arch = ["all", "arm64-v8a", "arm-v7a", "x86_64"]
cli-source = "MorpheApp/morphe-desktop"
cache_repo_dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.nis.app"
uptodown-dlurl = "https://inshorts.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/inshorts-formerly-news-in-shorts/inshorts-news-in-60-words-2"
dpi = ["nodpi", "anydpi", "auto"]
patches-source = "BholeyKaBhakt/revanced-patches-xtra"

# ── Automate ──────────────────────────────────────────────────────────────────
[automate-morphe-xtra]
enabled = true
app-name = "automate"
rv-brand = "morphe-xtra"
pkg-name = "com.llamalab.automate"
build-mode = "apk"
arch = ["all", "arm64-v8a", "arm-v7a", "x86_64"]
cli-source = "MorpheApp/morphe-desktop"
cache_repo_dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.llamalab.automate"
uptodown-dlurl = "https://automate-beta.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/llamalab/automate-llamalab"
dpi = ["nodpi", "anydpi", "auto"]
patches-source = "BholeyKaBhakt/revanced-patches-xtra"

# ── AutoSync ──────────────────────────────────────────────────────────────────
[autosync-morphe-xtra]
enabled = true
app-name = "autosync"
rv-brand = "morphe-xtra"
pkg-name = "com.ttxapps.autosync"
build-mode = "apk"
arch = ["all", "arm64-v8a", "x86_64"]
cli-source = "MorpheApp/morphe-desktop"
cache_repo_dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.ttxapps.autosync"
uptodown-dlurl = "https://autosync.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/metactrl/autosync-universal-cloud-sync-and-backup"
dpi = ["nodpi", "anydpi", "auto"]
patches-source = "BholeyKaBhakt/revanced-patches-xtra"

# ── Backdrops ─────────────────────────────────────────────────────────────────
[backdrops-morphe-xtra]
enabled = true
app-name = "backdrops"
rv-brand = "morphe-xtra"
pkg-name = "com.backdrops.wallpapers"
build-mode = "apk"
arch = ["all", "arm64-v8a", "arm-v7a", "x86_64"]
cli-source = "MorpheApp/morphe-desktop"
cache_repo_dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.backdrops.wallpapers"
uptodown-dlurl = "https://backdrops.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/backdrops/backdrops-wallpapers"
dpi = ["nodpi", "anydpi", "auto"]
patches-source = "BholeyKaBhakt/revanced-patches-xtra"
