enable-module-update = true
patches-version = "absolutelatest"
[speedtest-morphe-xtra]
enabled = true
app-name = "speedtest"
pkg-name = "org.zwanoo.android.speedtest"
rv-brand = "morphe-xtra"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/org.zwanoo.android.speedtest"
version = "latest"
build-mode = "apk"
arch = "multi"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://speedtest.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/ookla/speedtest"
dpi = "nodpi anydpi auto"
patches-source = "BholeyKaBhakt/revanced-patches-xtra"
