enable-module-update = true
patches-version = "absolutelatest"


[calcnote-morphe-binarymend]
enabled = true
app-name = "calcnote"
rv-brand = "morphe-binarymend"
pkg-name = "com.rocketshipapps.calcnote"
build-mode = "apk"
arch = "all arm64-v8a arm-v7a x86_64"
cli-source = "MorpheApp/morphe-desktop"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.rocketshipapps.calcnote"
uptodown-dlurl = "https://calcnote-notepad-calculator.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/burton999/calcnote-notepad-calculator"
dpi = "nodpi anydpi auto"
patches-source = "binarymend/morphe-patches"
