enable-module-update = true
patches-version = "absolutelatest"

# ── Pinterest (browzomje-patches) ─────────────────────────────────────────────
[pinterest-morphe-browzomje]
enabled = true
app-name = "pinterest"
rv-brand = "morphe-browzomje"
pkg-name = "com.pinterest"
build-mode = "apk"
arch = "all arm64-v8a arm-v7a x86_64"
cli-source = "MorpheApp/morphe-desktop"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.pinterest"
uptodown-dlurl = "https://pinterest.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pinterest/pinterest-one-destination-for-a-world-of-inspiration"
dpi = "nodpi anydpi auto"
patches-source = "browzomje/browzomje-patches"

[pinterest-morphe-browzomje-exp]
enabled = true
app-name = "pinterest"
rv-brand = "morphe-browzomje-exp"
pkg-name = "com.pinterest"
build-mode = "apk"
version = "latest"
arch = "all arm64-v8a arm-v7a x86_64"
cli-source = "MorpheApp/morphe-desktop"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.pinterest"
uptodown-dlurl = "https://pinterest.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pinterest/pinterest-one-destination-for-a-world-of-inspiration"
dpi = "nodpi anydpi auto"
patches-source = "browzomje/browzomje-patches"
