enable-module-update = true
patches-version = "absolutelatest"

[smash-hit-morphe-byehi98]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "smash-hit"
rv-brand = "morphe-byehi98"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.mediocre.smashhit"
build-mode = "apk"
arch = "all"
pkg-name = "com.mediocre.smashhit"
uptodown-dlurl = "https://smash-hit.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/mediocre/smash-hit/"
dpi = "nodpi anydpi auto"
patches-source = "byehi98/okish-morphe-patches"

[vector-morphe-byehi98]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "vector"
rv-brand = "morphe-byehi98"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.nekki.vector"
build-mode = "apk"
arch = "all"
pkg-name = "com.nekki.vector"
uptodown-dlurl = "https://vector.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/nekki/vector/"
dpi = "nodpi anydpi auto"
patches-source = "byehi98/okish-morphe-patches"

[hill-climb-racing-morphe-byehi98]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "hill-climb-racing"
rv-brand = "morphe-byehi98"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.fingersoft.hillclimb"
build-mode = "apk"
arch = "all"
pkg-name = "com.fingersoft.hillclimb"
uptodown-dlurl = "https://hill-climb-racing.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/fingersoft/hill-climb-racing/"
dpi = "nodpi anydpi auto"
patches-source = "byehi98/okish-morphe-patches"

[hill-climb-racing-morphe-byehi98-exp]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "hill-climb-racing"
rv-brand = "morphe-byehi98-exp"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.fingersoft.hillclimb"
version = "latest"
build-mode = "apk"
arch = "all"
pkg-name = "com.fingersoft.hillclimb"
uptodown-dlurl = "https://hill-climb-racing.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/fingersoft/hill-climb-racing/"
dpi = "nodpi anydpi auto"
patches-source = "byehi98/okish-morphe-patches"

[jetpack-joyride-morphe-byehi98]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "jetpack-joyride"
rv-brand = "morphe-byehi98"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.halfbrick.jetpackjoyride"
build-mode = "apk"
arch = "all"
pkg-name = "com.halfbrick.jetpackjoyride"
uptodown-dlurl = "https://jetpack-joyride.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/halfbrick-studios/jetpack-joyride/"
apkmirror-example-url = "https://www.apkmirror.com/apk/halfbrick-studios/jetpack-joyride/jetpack-joyride-1-104-1-release/"
dpi = "nodpi anydpi auto"
patches-source = "byehi98/okish-morphe-patches"

[jetpack-joyride-morphe-byehi98-exp]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "jetpack-joyride"
rv-brand = "morphe-byehi98-exp"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.halfbrick.jetpackjoyride"
version = "latest"
build-mode = "apk"
arch = "all"
pkg-name = "com.halfbrick.jetpackjoyride"
uptodown-dlurl = "https://jetpack-joyride.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/halfbrick-studios/jetpack-joyride/"
apkmirror-example-url = "https://www.apkmirror.com/apk/halfbrick-studios/jetpack-joyride/jetpack-joyride-1-104-1-release/"
dpi = "nodpi anydpi auto"
patches-source = "byehi98/okish-morphe-patches"
