enable-module-update = true
patches-version = "absolutelatest"

[chess-morphe-prathxm]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "chess"
rv-brand = "morphe-prathxm"
cache_repo_dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.chess"
version = "auto"
build-mode = "apk"
arch = ["all"]
pkg-name = "com.chess"
uptodown-dlurl = "https://chess.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/chess-com/chess-play-learn/"
apkmirror-example-url = "https://www.apkmirror.com/apk/chess-com/chess-play-learn/chess-com-do-you-miss-us-4-10-6-googleplay-release/"
dpi = ["nodpi", "anydpi", "auto"]
patches-source = "PrathxmOp/Prathxm-Patches"

[chess-morphe-prathxm-clone]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "chess"
rv-brand = "morphe-prathxm-clone"
cache_repo_dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.chess"
version = "auto"
build-mode = "apk"
arch = ["all"]
pkg-name = "com.chess"
uptodown-dlurl = "https://chess.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/chess-com/chess-play-learn/"
apkmirror-example-url = "https://www.apkmirror.com/apk/chess-com/chess-play-learn/chess-com-do-you-miss-us-4-10-6-googleplay-release/"
dpi = ["nodpi", "anydpi", "auto"]
patches-source = "PrathxmOp/Prathxm-Patches"
included-patches = ["'Clone Chess.com'"]
