[brave-beta-morphe-dh6k-arm64-v8a]
enabled = true
app-name = "brave-beta"
rv-brand = "morphe-dh6k"
build-mode = "apk"
arch = "arm64-v8a"
pkg-name = "com.brave.browser.beta"
cli-source = "MorpheApp/morphe-desktop"
patches-source = "dh6k/morphe-patches"
repo-dlurl = "https://github.com/brave/brave-browser/releases"
repo-dlurl-release-name-filter = "beta"
version = "beta"
