[brave-nightly-morphe-dh6k-arm64-v8a]
enabled = true
app-name = "brave-nightly"
rv-brand = "morphe-dh6k"
build-mode = "apk"
arch = "arm64-v8a"
pkg-name = "com.brave.browser_nightly"
cli-source = "MorpheApp/morphe-desktop"
patches-source = "dh6k/morphe-patches"
repo-dlurl = "https://github.com/brave/brave-browser/releases"
repo-dlurl-filter = "(BraveMonoarm64|MonoArm64)\\.apk$"
repo-dlurl-release-name-filter = "^Nightly v"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.brave.browser_nightly"
version = "latest"

[brave-nightly-morphe-dh6k-arm-v7a]
enabled = true
app-name = "brave-nightly"
rv-brand = "morphe-dh6k"
build-mode = "apk"
arch = "arm-v7a"
pkg-name = "com.brave.browser_nightly"
cli-source = "MorpheApp/morphe-desktop"
patches-source = "dh6k/morphe-patches"
repo-dlurl = "https://github.com/brave/brave-browser/releases"
repo-dlurl-filter = "(BraveMonoarm|MonoArm)\\.apk$"
repo-dlurl-release-name-filter = "^Nightly v"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.brave.browser_nightly"
version = "latest"

[brave-nightly-morphe-dh6k-x86_64]
enabled = true
app-name = "brave-nightly"
rv-brand = "morphe-dh6k"
build-mode = "apk"
arch = "x86_64"
pkg-name = "com.brave.browser_nightly"
cli-source = "MorpheApp/morphe-desktop"
patches-source = "dh6k/morphe-patches"
repo-dlurl = "https://github.com/brave/brave-browser/releases"
repo-dlurl-filter = "(BraveMonox64|Monox64)\\.apk$"
repo-dlurl-release-name-filter = "^Nightly v"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.brave.browser_nightly"
version = "latest"

[brave-nightly-morphe-dh6k-x86]
enabled = true
app-name = "brave-nightly"
rv-brand = "morphe-dh6k"
build-mode = "apk"
arch = "x86"
pkg-name = "com.brave.browser_nightly"
cli-source = "MorpheApp/morphe-desktop"
patches-source = "dh6k/morphe-patches"
repo-dlurl = "https://github.com/brave/brave-browser/releases"
repo-dlurl-filter = "(BraveMonox86|Monox86)\\.apk$"
repo-dlurl-release-name-filter = "^Nightly v"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.brave.browser_nightly"
version = "latest"
