enable-module-update = true
patches-version = "absolutelatest"


[gboard-morphe-jasonwu1994-adobo]
enabled = true
app-name = "gboard"
rv-brand = "morphe-jasonwu1994-adobo"
build-mode = "both"
arch = "multi"
pkg-name = "com.google.android.inputmethod.latin"
patches-source = "'jasonwu1994/Gboard-patches' 'jkennethcarino/adobo'"
included-patches = " | 'Enable clipboard in incognito' 'Enable voice typing in incognito'"
exclusive-patches = "'jkennethcarino/adobo'"
excluded-patches = "'Package Rename' | "
patcher-args = "-f --continue-on-error"
cli-source = "MorpheApp/morphe-desktop"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard/"
apkmirror-example-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard/gboard-the-google-keyboard-17-8-7-939743344-release/"
version-filter = "!lite|go"
version = "17.8.7.939743344"
dpi = "nodpi anydpi auto"


[gboard-morphe-jasonwu1994-adobo-clone]
enabled = true
app-name = "gboard"
rv-brand = "morphe-jasonwu1994-adobo-clone"
build-mode = "apk"
arch = "multi"
patches-source = "'jasonwu1994/Gboard-patches' 'jkennethcarino/adobo'"
included-patches = " | 'Enable clipboard in incognito' 'Enable voice typing in incognito'"
exclusive-patches = "'jkennethcarino/adobo'"
pkg-name = "com.google.android.inputmethod.latin"
cli-source = "MorpheApp/morphe-desktop"
patcher-args = "-f --continue-on-error"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard/"
apkmirror-example-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard/gboard-the-google-keyboard-17-8-7-939743344-release/"
version-filter = "!lite|go"
version = "17.8.7.939743344"
dpi = "nodpi anydpi auto"

