enable-module-update = true
patches-version = "absolutelatest"


[gboard-morphe-jasonwu1994-adobo]
enabled = true
app-name = "gboard"
rv-brand = "morphe-jasonwu1994-adobo"
build-mode = "both"
arch = "all"
pkg-name = "com.google.android.inputmethod.latin"
patches-source = "'jasonwu1994/Gboard-patches' 'jkennethcarino/adobo'"
included-patches = " | 'Enable clipboard in incognito' 'Enable voice typing in incognito'"
exclusive-patches = "'jkennethcarino/adobo'"
excluded-patches = "'Package Rename' | "
patcher-args = "--continue-on-error"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://gboard-go.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard"
dpi = "nodpi anydpi auto"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.inputmethod.latin"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.google.android.inputmethod.latin"

[gboard-morphe-jasonwu1994-adobo-clone]
enabled = true
app-name = "gboard"
rv-brand = "morphe-jasonwu1994-adobo-clone"
build-mode = "apk"
arch = "all"
patches-source = "'jasonwu1994/Gboard-patches' 'jkennethcarino/adobo'"
included-patches = " | 'Enable clipboard in incognito' 'Enable voice typing in incognito'"
exclusive-patches = "'jkennethcarino/adobo'"
pkg-name = "com.google.android.inputmethod.latin"
cli-source = "MorpheApp/morphe-desktop"
patcher-args = "--continue-on-error"
uptodown-dlurl = "https://gboard-go.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard"
dpi = "nodpi anydpi auto"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.inputmethod.latin"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.google.android.inputmethod.latin"
