enable-module-update = true
patches-version = "absolutelatest"

[prime-video-morphe-hoodles]
enabled = true
app-name = "prime-video"
rv-brand = "morphe-hoodles"
pkg-name = "com.amazon.avod.thirdpartyclient"
build-mode = "apk"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.amazon.avod.thirdpartyclient"
version = "latest"
arch = "both"
cli-source = "MorpheApp/morphe-desktop"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video/"
uptodown-dlurl = "https://amazon-video.en.uptodown.com/android"
dpi = "nodpi anydpi auto"
patches-source = "hoo-dles/morphe-patches"
excluded-patches = "'Rename Shared Permissions'"

[prime-video-morphe-hoodles-shared]
enabled = true
app-name = "prime-video"
rv-brand = "morphe-hoodles-shared"
pkg-name = "com.amazon.avod.thirdpartyclient"
build-mode = "apk"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.amazon.avod.thirdpartyclient"
version = "latest"
arch = "both"
cli-source = "MorpheApp/morphe-desktop"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video/"
uptodown-dlurl = "https://amazon-video.en.uptodown.com/android"
dpi = "nodpi anydpi auto"
patches-source = "hoo-dles/morphe-patches"

[xrecorder-morphe-hoodles]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "xrecorder"
rv-brand = "morphe-hoodles"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/videoeditor.videorecorder.screenrecorder"
version = "latest"
build-mode = "apk"
arch = "all"
pkg-name = "videoeditor.videorecorder.screenrecorder"
uptodown-dlurl = "https://videoeditor-videorecorder-screenrecorder.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/inshot-inc-2/screen-recorder-video-recorder-xrecorder"
dpi = "nodpi anydpi auto"
patches-source = "hoo-dles/morphe-patches"

[camscanner-morphe-hoodles]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "camscanner"
rv-brand = "morphe-hoodles"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.intsig.camscanner"
version = "auto"
build-mode = "apk"
arch = "arm64-v8a"
pkg-name = "com.intsig.camscanner"
uptodown-dlurl = "https://camscanner-pdf-creator.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/intsig-pte/camscanner-phone-pdf-creator"
apkpure-dlurl = "https://apkpure.com/camscanner-scanner-pdf-maker/com.intsig.camscanner"
apkcombo-dlurl = "https://apkcombo.com/camscanner/com.intsig.camscanner"
dpi = "nodpi anydpi auto"
patches-source = "hoo-dles/morphe-patches"

[smart-launcher-6-morphe-hoodles]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "smart-launcher-6"
rv-brand = "morphe-hoodles"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/ginlemon.flowerfree"
version = "latest"
build-mode = "apk"
arch = "all"
pkg-name = "ginlemon.flowerfree"
uptodown-dlurl = "https://smart-launcher.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/smart-launcher"
dpi = "nodpi anydpi auto"
patches-source = "hoo-dles/morphe-patches"

[nova-launcher-morphe-hoodles]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "nova-launcher"
rv-brand = "morphe-hoodles"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.teslacoilsw.launcher"
version = "latest"
build-mode = "apk"
arch = "all"
pkg-name = "com.teslacoilsw.launcher"
uptodown-dlurl = "https://nova-launcher.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/teslacoil_software/nova-launcher"
dpi = "nodpi anydpi auto"
patches-source = "hoo-dles/morphe-patches"

[xodo-morphe-hoodles]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "xodo"
rv-brand = "morphe-hoodles"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.xodo.pdf.reader"
version = "latest"
build-mode = "apk"
arch = "multi"
pkg-name = "com.xodo.pdf.reader"
uptodown-dlurl = "https://xodo-pdf-reader-editor.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/xodo-technologies-inc/xodo-pdf-reader-editor"
dpi = "nodpi anydpi auto"
patches-source = "hoo-dles/morphe-patches"

[solid-explorer-morphe-hoodles]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "solid-explorer"
rv-brand = "morphe-hoodles"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/pl.solidexplorer2"
version = "latest"
build-mode = "apk"
arch = "all"
pkg-name = "pl.solidexplorer2"
uptodown-dlurl = "https://solid-explorer-file-manager.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/neatbytes/solid-explorer-file-manager/"
dpi = "nodpi anydpi auto"
patches-source = "hoo-dles/morphe-patches"
