enable-module-update = true
patches-version = "absolutelatest"
[tiktok-morphe-icysymmetra]
enabled = true
app-name = "tiktok"
pkg-name = "com.zhiliaoapp.musically"
rv-brand = "morphe-icysymmetra"
build-mode = "apk"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
patches-source = "icysymmetra/tiktok-patches-for-morphe"

