enable-module-update = true

# ── Drofus (morphe-lain) ─────────────────────────────────────────────────────
[Drofus-Morphe-Lain]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "Drofus"
engine-brand = "Morphe"
patch-brand = "Lain"
cache_repo_dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.mixapplications.rufus"
build-mode = "apk"
arch = "arm64-v8a arm-v7a"
pkg-name = "com.mixapplications.rufus"
uptodown-dlurl = "https://rufus-unofficial.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/mixapplications/drofus-iso2usb"
patches-source = "kiraio-moe/Lain-Patches"
