enable-module-update = true
patches-version = "absolutelatest"

# ── Droufus (morphe-lain) ─────────────────────────────────────────────────────
[droufus-morphe-lain]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "droufus"
rv-brand = "morphe-lain"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.mixapplications.rufus"
build-mode = "apk"
arch = "arm64-v8a arm-v7a"
pkg-name = "com.mixapplications.rufus"
uptodown-dlurl = "https://rufus-unofficial.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/mixapplications/drofus-iso2usb"
dpi = "nodpi anydpi auto"
patches-source = "kiraio-moe/Lain-Patches"
