enable-module-update = true
patches-version = "absolutelatest"

[youtube-morphe-exp]
enabled = true
app-name = "youtube"
rv-brand = "morphe-exp"
build-mode = "both"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.google.android.youtube"
version = "exp"
pkg-name = "com.google.android.youtube"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"
# github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.google.android.youtube"
apkpure-dlurl = "https://apkpure.com/youtube-app/com.google.android.youtube"
apkcombo-dlurl = "https://apkcombo.com/youtube/com.google.android.youtube"
patches-source = "MorpheApp/morphe-patches"
patcher-args = "-OdarkThemeBackgroundColor=#000000 "
included-patches = "'Theme'"

arch = "all"

[youtube-music-morphe-exp]
enabled = true
app-name = "youtube-music"
rv-brand = "morphe-exp"
build-mode = "both"
arch = "multi"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.google.android.apps.youtube.music"
version = "exp"
pkg-name = "com.google.android.apps.youtube.music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"
# github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.google.android.apps.youtube.music"
apkpure-dlurl = "https://apkpure.com/youtube-music/com.google.android.apps.youtube.music"
apkcombo-dlurl = "https://apkcombo.com/youtube-music/com.google.android.apps.youtube.music"
patches-source = "MorpheApp/morphe-patches"
patcher-args = "-OdarkThemeBackgroundColor=#000000 "
included-patches = "'Theme'"
