enable-module-update = true
patches-version = "absolutelatest"

[ClashOfClans-APKSigner-Nulls]
enabled = true
cli-source = "none"
cli-source-host = "none"
app-name = "Clash of Clans"
engine-brand = "APKSigner"
patch-brand = "Nulls"
build-mode = "apk"
arch = "all"
pkg-name = "nullsclash.night.rel"
direct-dlurl = "http://dnull.xyz/latest_coc"
patches-source = "none"
patches-source-host = "none"
[ClashRoyale-APKSigner-Nulls]
enabled = true
cli-source = "none"
cli-source-host = "none"
app-name = "Clash Royale"
engine-brand = "APKSigner"
patch-brand = "Nulls"
build-mode = "apk"
arch = "all"
pkg-name = "nullsroyale.rel.free"
direct-dlurl = "http://dnull.xyz/latest_cr"
patches-source = "none"
patches-source-host = "none"
[BrawlStars-APKSigner-Nulls]
enabled = true
cli-source = "none"
cli-source-host = "none"
app-name = "Brawl Stars"
engine-brand = "APKSigner"
patch-brand = "Nulls"
build-mode = "apk"
arch = "all"
pkg-name = "daniillnull.nulls.brawlstars"
direct-dlurl = "http://dnull.xyz/latest_bs"
patches-source = "none"
patches-source-host = "none"
