enable-module-update = true
patches-version = "absolutelatest"

[clash-of-clans-morphe-nulls]
enabled = true
cli-source = "none"
cli-source-host = "none"
app-name = "clash-of-clans"
rv-brand = "nulls"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/nullsclash.night.rel"
build-mode = "apk"
arch = "arm64-v8a arm-v7a"
pkg-name = "nullsclash.night.rel"
direct-dlurl = "http://dnull.xyz/latest_coc"
dpi = "nodpi anydpi auto"
patches-source = "none"
patches-source-host = "none"

[clash-royale-morphe-nulls]
enabled = true
cli-source = "none"
cli-source-host = "none"
app-name = "clash-royale"
rv-brand = "nulls"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/nullsroyale.rel.free"
build-mode = "apk"
arch = "arm64-v8a arm-v7a"
pkg-name = "nullsroyale.rel.free"
direct-dlurl = "http://dnull.xyz/latest_cr"
dpi = "nodpi anydpi auto"
patches-source = "none"
patches-source-host = "none"

[brawl-stars-morphe-nulls]
enabled = true
cli-source = "none"
cli-source-host = "none"
app-name = "brawl-stars"
rv-brand = "nulls"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/daniillnull.nulls.brawlstars"
build-mode = "apk"
arch = "arm64-v8a arm-v7a"
pkg-name = "daniillnull.nulls.brawlstars"
direct-dlurl = "http://dnull.xyz/latest_bs"
dpi = "nodpi anydpi auto"
patches-source = "none"
patches-source-host = "none"
