enable-module-update = true
patches-version = "absolutelatest"
[truecaller-morphe-paresh]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "truecaller"
rv-brand = "morphe-paresh"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.truecaller"
build-mode = "both"
arch = "all arm64-v8a arm-v7a"
pkg-name = "com.truecaller"
uptodown-dlurl = "https://truecaller.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/true-software-scandinavia-ab/truecaller-caller-id-block"
dpi = "nodpi anydpi auto"
patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-host = "gitlab"

[fing-morphe-paresh]
enabled = true
app-name = "fing"
rv-brand = "morphe-paresh"
build-mode = "apk"
pkg-name = "com.overlook.android.fing"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://fing-network-tools.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/fing-limited/fing-network-tools"
dpi = "nodpi anydpi auto"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.overlook.android.fing"
patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-host = "gitlab"

arch = "all"

[fing-morphe-paresh-exp]
enabled = true
app-name = "fing"
rv-brand = "morphe-paresh-exp"
version = "latest"
build-mode = "apk"
pkg-name = "com.overlook.android.fing"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://fing-network-tools.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/fing-limited/fing-network-tools"
dpi = "nodpi anydpi auto"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.overlook.android.fing"
patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-host = "gitlab"

arch = "all"

[proton-vpn-morphe-paresh]
enabled = true
app-name = "proton-vpn"
rv-brand = "morphe-paresh"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/ch.protonvpn.android"
build-mode = "apk"
pkg-name = "ch.protonvpn.android"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"
prefer-dl-mode = "bundle"
patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-host = "gitlab"
dpi = "120-640dpi"

arch = "all"

[proton-vpn-morphe-paresh-exp]
enabled = true
app-name = "proton-vpn"
rv-brand = "morphe-paresh-exp"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/ch.protonvpn.android"
version = "latest"
build-mode = "apk"
pkg-name = "ch.protonvpn.android"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"
prefer-dl-mode = "bundle"
patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-host = "gitlab"
dpi = "120-640dpi"

arch = "all"

[jiohotstar-morphe-paresh]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "jiohotstar"
rv-brand = "morphe-paresh"
build-mode = "apk"
pkg-name = "in.startv.hotstar"
apkmirror-dlurl = "https://www.apkmirror.com/apk/jiostar-india-private-limited/jiohotstar-4/"
apkmirror-example-url = "https://www.apkmirror.com/apk/jiostar-india-private-limited/jiohotstar-4/jiohotstar-26-08-03-2-release/"
dpi = "nodpi anydpi auto"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/in.startv.hotstar"
patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-host = "gitlab"

[jiohotstar-morphe-paresh-exp]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "jiohotstar"
rv-brand = "morphe-paresh-exp"
version = "latest"
build-mode = "apk"
pkg-name = "in.startv.hotstar"
apkmirror-dlurl = "https://www.apkmirror.com/apk/jiostar-india-private-limited/jiohotstar-4/"
apkmirror-example-url = "https://www.apkmirror.com/apk/jiostar-india-private-limited/jiohotstar-4/jiohotstar-26-08-03-2-release/"
dpi = "nodpi anydpi auto"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/in.startv.hotstar"
patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-host = "gitlab"

[sdmaid-morphe-paresh]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "sdmaid"
rv-brand = "morphe-paresh"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/eu.darken.sdmse"
build-mode = "apk"
arch = "all"
pkg-name = "eu.darken.sdmse"
uptodown-dlurl = "https://sd-maid-se.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/darken/sd-maid-2-se-system-cleaner"
apkmirror-example-url = "https://www.apkmirror.com/apk/darken/sd-maid-2-se-system-cleaner/sd-maid-2-se-system-cleaner-2-0-3-rc0-release"
dpi = "nodpi anydpi auto"
patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-host = "gitlab"

[sdmaid-morphe-paresh-exp]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "sdmaid"
rv-brand = "morphe-paresh-exp"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/eu.darken.sdmse"
version = "latest"
build-mode = "apk"
arch = "all"
pkg-name = "eu.darken.sdmse"
uptodown-dlurl = "https://sd-maid-se.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/darken/sd-maid-2-se-system-cleaner"
apkmirror-example-url = "https://www.apkmirror.com/apk/darken/sd-maid-2-se-system-cleaner/sd-maid-2-se-system-cleaner-2-0-3-rc0-release"
dpi = "nodpi anydpi auto"
patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-host = "gitlab"
