enable-module-update = true
patches-version = "absolutelatest"

[instagram-morphe-piko]
enabled = true
app-name = "instagram"
rv-brand = "morphe-piko"
build-mode = "apk"
arch = "both64"
pkg-name = "com.instagram.android"
patcher-args = "--continue-on-error"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
#archive-dlurl = "https://archive.org/download/geologically/apks/com.instagram.android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
dpi = "nodpi anydpi auto"
patches-source = "crimera/piko"

[x-morphe-xshim-piko]
enabled = true 
app-name = "x"
rv-brand = "morphe-xshim-piko"
build-mode = "apk"
version = "latest"
pkg-name = "com.twitter.android"
patcher-args = "--continue-on-error"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
dpi = "nodpi anydpi auto"
patches-source = "'inotia00/x-shim' 'crimera/piko'"
patches-source-host = "'gitlab' 'github'"
included-patches = "'Dynamic Color'"

