enable-module-update = true
patches-version = "absolutelatest"
[discord-npatch-revenge]
enabled = true 
app-name = "discord"
rv-brand = "npatch-revenge"
build-mode = "apk"
arch = "all"
cli-source = "7723mod/NPatch"
patches-source = "revenge-mod/revenge-xposed"
patcher-args = "-l 0"
# uptodown-dlurl = "https://discord-chat-for-gamers.en.uptodown.com/android"
apkcombo-dlurl = "https://apkcombo.com/discord/com.discord"
apkmirror-dlurl = "https://www.apkmirror.com/apk/discord/discord-chat-for-gamers"
apkmirror-example-url = "https://www.apkmirror.com/apk/discord/discord-chat-for-gamers/discord-talk-play-hang-out-340-13-stable-release/"
