enable-module-update = true
patches-version = "absolutelatest"
[amazon-india-morphe-rushiranpise]
enabled = true
app-name = "amazon-india"
rv-brand = "morphe-rushiranpise"
build-mode = "apk"
pkg-name = "in.amazon.mShop.android.shopping"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://amazon-india.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-india-shop-pay/"
dpi = "nodpi anydpi auto"
patches-source = "rushiranpise/morphe-patches"
included-patches = "'Dark Mode' 'Open Links in Browser'"
excluded-patches = "'Hide Rufus Tab'"
custom-microg-patches = "'None'"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/in.amazon.mShop.android.shopping"
version = "latest"

arch = "all"

[adobe-acrobat-morphe-rushiranpise]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "adobe-acrobat"
rv-brand = "morphe-rushiranpise"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.adobe.reader"
version = "latest"
build-mode = "apk"
arch = "both64"
pkg-name = "com.adobe.reader"
uptodown-dlurl = "https://adobe-reader.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/adobe-acrobat/"
dpi = "nodpi anydpi auto"
patches-source = "rushiranpise/morphe-patches"
custom-microg-patches = "'None'"

[microsoft-word-morphe-rushiranpise]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "microsoft-word"
rv-brand = "morphe-rushiranpise"
custom-microg-patches = "'None'"
build-mode = "apk"
arch = "multi"
pkg-name = "com.microsoft.office.word"
uptodown-dlurl = "https://microsoft-word-preview.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/microsoft-corporation/word/"
dpi = "nodpi anydpi auto"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.microsoft.office.word"
patches-source = "rushiranpise/morphe-patches"

[microsoft-excel-morphe-rushiranpise]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "microsoft-excel"
rv-brand = "morphe-rushiranpise"
custom-microg-patches = "'None'"
build-mode = "apk"
arch = "multi"
pkg-name = "com.microsoft.office.excel"
uptodown-dlurl = "https://microsoft-excel-preview.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/microsoft-corporation/excel/"
dpi = "nodpi anydpi auto"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.microsoft.office.excel"
patches-source = "rushiranpise/morphe-patches"

[pc-remote-morphe-rushiranpise]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "pc-remote"
rv-brand = "morphe-rushiranpise"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.monect.portable"
version = "latest"
custom-microg-patches = "'None'"
build-mode = "apk"
pkg-name = "com.monect.portable"
uptodown-dlurl = "https://monect-pc-remote.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/monect-suzhou-co-ltd/pc-remote/"
dpi = "nodpi anydpi auto"
patches-source = "rushiranpise/morphe-patches"

arch = "all"

[oxygen-updater-morphe-rushiranpise]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "oxygen-updater"
rv-brand = "morphe-rushiranpise"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.arjanvlek.oxygenupdater"
version = "latest"
custom-microg-patches = "'None'"
build-mode = "apk"
pkg-name = "com.arjanvlek.oxygenupdater"
repo-dlurl = "https://github.com/oxygen-updater/os-updater"
patches-source = "rushiranpise/morphe-patches"

[windscribe-vpn-morphe-rushiranpise]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "windscribe-vpn"
rv-brand = "morphe-rushiranpise"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.windscribe.vpn"
version = "latest"
custom-microg-patches = "'None'"
build-mode = "apk"
arch = "all"
pkg-name = "com.windscribe.vpn"
uptodown-dlurl = "https://windscribe.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/windscribe/windscribe-vpn"
apkcombo-dlurl = "https://apkcombo.com/windscribe/com.windscribe.vpn"
dpi = "nodpi anydpi auto"
patches-source = "rushiranpise/morphe-patches"

[1111-warp-morphe-rushiranpise]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "1111-warp"
rv-brand = "morphe-rushiranpise"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.cloudflare.onedotonedotonedotone"
version = "latest"
custom-microg-patches = "'None'"
build-mode = "apk"
arch = "all"
pkg-name = "com.cloudflare.onedotonedotonedotone"
uptodown-dlurl = "https://1-1-1-1.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/cloudflare/1-1-1-1-faster-safer-internet"
dpi = "nodpi anydpi auto"
patches-source = "rushiranpise/morphe-patches"

[adguard-morphe-rushiranpise]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "adguard"
rv-brand = "morphe-rushiranpise"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.adguard.android"
version = "latest"
custom-microg-patches = "'None'"
build-mode = "apk"
arch = "all"
pkg-name = "com.adguard.android"
uptodown-dlurl = "https://adguard-for-android.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adguard-software-limited/adguard"
dpi = "nodpi anydpi auto"
patches-source = "rushiranpise/morphe-patches"

[beta-maniac-morphe-rushiranpise]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "beta-maniac"
rv-brand = "morphe-rushiranpise"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/it.mirko.beta"
version = "latest"
build-mode = "apk"
arch = "all"
pkg-name = "it.mirko.beta"
uptodown-dlurl = "https://beta-maniac.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/mirko-dimartino/beta-maniac-life-of-a-beta-tester-2"
dpi = "nodpi anydpi auto"
patches-source = "rushiranpise/morphe-patches"

[duolingo-morphe-rushiranpise]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "duolingo"
rv-brand = "morphe-rushiranpise"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.duolingo"
version = "latest"
build-mode = "apk"
arch = "both"
pkg-name = "com.duolingo"
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/duolingo-learn-languages-free/"
apkmirror-example-dlurl = "https://www.apkmirror.com/apk/duolingo/duolingo-learn-languages-free/duolingo-learn-languages-free-6-93-6-release/"
dpi = "nodpi anydpi auto"
patches-source = "rushiranpise/morphe-patches"
