enable-module-update = true
patches-version = "dev"
[amazon-alexa-signed]
enabled = true
app-name = "amazon-alexa"
rv-brand = "signed"
build-mode = "apk"
cli-source = "apksigner"
pkg-name = "com.amazon.dee.app"
cli-source-host = "none"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.amazon.dee.app"
patches-source = "none"
patches-source-host = "none"
arch = "all"
prefer-dl-mode = "bundle"
uptodown-dlurl = "https://alexa.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-alexa/"
dpi = "120-480dpi 480-640dpi"
