enable-module-update = true
patches-version = "dev"
[AmazonAlexa-APKSigner-Signed]
enabled = true
app-name = "Amazon Alexa"
patch-brand = "Signed"
build-mode = "apk"
cli-type = "apksigner"
pkg-name = "com.amazon.dee.app"
cli-source-host = "none"
cache_repo_dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.amazon.dee.app"
patches-source = "none"
patches-source-host = "none"
prefer-dl-mode = "bundle"
uptodown-dlurl = "https://alexa.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-alexa/"
