[bitwarden-morphe-stylus]
enabled = true
app-name = "bitwarden"
rv-brand = "morphe-stylus"
build-mode = "apk"
pkg-name = "com.x8bit.bitwarden"
cli-source = "MorpheApp/morphe-desktop"
repo-dlurl = "https://github.com/bitwarden/android"
repo-dlurl-filter = "fdroid.apk"
repo-dlurl-tag-filter = "bwpm"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.x8bit.bitwarden"
version = "latest"
patches-source = "ch3thanhs/stylus"

[bitwarden-morphe-stylus]
enabled = true
app-name = "bitwarden"
rv-brand = "morphe-stylus"
build-mode = "apk"
pkg-name = "com.x8bit.bitwarden"
cli-source = "MorpheApp/morphe-desktop"
repo-dlurl = "https://github.com/bitwarden/android"
repo-dlurl-filter = "fdroid.apk"
repo-dlurl-tag-filter = "bwpm"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.x8bit.bitwarden"
patches-source = "ch3thanhs/stylus"

[bitwarden-morphe-stylus-exp]
enabled = true
app-name = "bitwarden"
rv-brand = "morphe-stylus-exp"
build-mode = "apk"
pkg-name = "com.x8bit.bitwarden"
cli-source = "MorpheApp/morphe-desktop"
repo-dlurl = "https://github.com/bitwarden/android"
repo-dlurl-filter = "fdroid.apk"
repo-dlurl-tag-filter = "bwpm"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.x8bit.bitwarden"
version = "latest"
patches-source = "ch3thanhs/stylus"
