# --- Batch TOML Part 5 (8 distinct apps, 8 builds) ---


[YouTube-Morphe-Experimental]
enabled = true
app-name = "YouTube"
engine-brand = "Morphe"
sub-variant = "Experimental"
build-mode = "both"
arch = "all arm64-v8a arm-v7a x86_64"
version = "exp"
pkg-name = "com.google.android.youtube"
cli-source = "MorpheApp/morphe-desktop"
patches-source = "MorpheApp/morphe-patches"
included-patches = "'Theme'"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
apkpure-dlurl = "https://apkpure.com/youtube-app/com.google.android.youtube"
apkcombo-dlurl = "https://apkcombo.com/youtube/com.google.android.youtube"
cache_repo_dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.google.android.youtube"



[Ventusky-Morphe-Hoodles]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "Ventusky"
engine-brand = "Morphe"
patch-brand = "Hoodles"
cache_repo_dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/cz.ackee.ventusky"
build-mode = "apk"
arch = "all arm64-v8a arm-v7a x86_64"
pkg-name = "cz.ackee.ventusky"
uptodown-dlurl = "https://ventusky-weather-maps-and-radar.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/ventusky/ventusky-weather-maps-radar"
patches-source = "hoo-dles/morphe-patches"



[SmashHit-Morphe-Byehi98]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "Smash Hit"
engine-brand = "Morphe"
patch-brand = "Byehi98"
cache_repo_dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.mediocre.smashhit"
build-mode = "apk"
arch = "all arm64-v8a arm-v7a x86_64"
pkg-name = "com.mediocre.smashhit"
uptodown-dlurl = "https://smash-hit.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/mediocre/smash-hit/"
patches-source = "byehi98/okish-morphe-patches"



[PodcastAddict-Morphe-Hoodles]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "Podcast Addict"
engine-brand = "Morphe"
patch-brand = "Hoodles"
cache_repo_dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.bambuna.podcastaddict"
build-mode = "apk"
arch = "all arm64-v8a arm-v7a x86_64"
pkg-name = "com.bambuna.podcastaddict"
uptodown-dlurl = "https://podcast-addict.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/xavier-guillemane/podcast-addict"
patches-source = "hoo-dles/morphe-patches"



[MerriamWebsterDictionary-Morphe-Hoodles]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "Merriam-Webster Dictionary"
engine-brand = "Morphe"
patch-brand = "Hoodles"
cache_repo_dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.merriamwebster"
build-mode = "apk"
arch = "all arm64-v8a arm-v7a x86_64"
pkg-name = "com.merriamwebster"
uptodown-dlurl = "https://merriam-webster.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/merriam-webster-inc/dictionary-merriam-webster"
patches-source = "hoo-dles/morphe-patches"



[GitHub-Morphe-Hoodles-Stylus]
enabled = true
app-name = "GitHub"
engine-brand = "Morphe"
patch-brand = "Hoodles-Stylus"
build-mode = "apk"
arch = "all arm64-v8a arm-v7a x86_64"
pkg-name = "com.github.android"
cli-source = "MorpheApp/morphe-desktop"
apkmirror-dlurl = "https://www.apkmirror.com/apk/github/github-2"
apkmirror-example-url = "https://www.apkmirror.com/apk/github/github-2/github-1-202-0-release/"
cache_repo_dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.github.android"
patches-source = "'hoo-dles/morphe-patches' 'ch3thanhs/stylus'"
included-patches = "'AMOLED dark theme' | 'Force system font (including monospace) (GitHub)'"



[ClashOfClans-APKSigner-Nulls]
enabled = true
cli-source = "none"
cli-source-host = "none"
app-name = "Clash of Clans"
engine-brand = "APKSigner"
patch-brand = "Nulls"
build-mode = "apk"
arch = "all"
pkg-name = "nullsclash.night.rel"
direct-dlurl = "http://dnull.xyz/latest_coc"
patches-source = "none"
patches-source-host = "none"


[Backdrops-Morphe-BholeyKaBhakt]
enabled = true
app-name = "Backdrops"
engine-brand = "Morphe"
patch-brand = "BholeyKaBhakt"
pkg-name = "com.backdrops.wallpapers"
build-mode = "apk"
arch = "all arm64-v8a arm-v7a x86_64"
cli-source = "MorpheApp/morphe-desktop"
cache_repo_dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.backdrops.wallpapers"
uptodown-dlurl = "https://backdrops.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/backdrops/backdrops-wallpapers"
patches-source = "BholeyKaBhakt/revanced-patches-xtra"

