# --- Batch TOML Part 8/10 (13 apps) ---


[x-morphe-piko-materialyou-exp]
enabled = true
app-name = "x"
rv-brand = "morphe-piko-materialyou-exp"
build-mode = "apk"
arch = "all"
version = "latest"
pkg-name = "com.twitter.android"
cli-source = "MorpheApp/morphe-desktop"
patches-source = "crimera/piko"
patches-source-host = "github"
included-patches = "'Dynamic Color'"
patcher-args = "--continue-on-error"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.twitter.android"
dpi = "nodpi anydpi auto"


enable-module-update = true
patches-version = "absolutelatest"


[discord-npatch-revenge]
enabled = true 
app-name = "discord"
pkg-name = "com.discord"
rv-brand = "npatch-revenge"
build-mode = "apk"
arch = "all"
cli-source = "7723mod/NPatch"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.discord"
patches-source = "revenge-mod/revenge-xposed"
patcher-args = "-l 0"
dpi = "nodpi anydpi auto"
uptodown-dlurl = "https://discord-chat-for-gamers.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/discord/discord-chat-for-gamers"
apkmirror-example-url = "https://www.apkmirror.com/apk/discord/discord-chat-for-gamers/discord-talk-play-hang-out-341-13-stable-release/"


enable-module-update = true
patches-version = "absolutelatest"


[microsoft-word-morphe-rushiranpise]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "microsoft-word"
rv-brand = "morphe-rushiranpise"
custom-microg-patches = "'None'"
build-mode = "apk"
arch = "all arm64-v8a arm-v7a x86_64"
pkg-name = "com.microsoft.office.word"
uptodown-dlurl = "https://microsoft-word-preview.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/microsoft-corporation/word/"
dpi = "nodpi anydpi auto"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.microsoft.office.word"
patches-source = "rushiranpise/morphe-patches"



[microsoft-excel-morphe-rushiranpise]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "microsoft-excel"
rv-brand = "morphe-rushiranpise"
custom-microg-patches = "'None'"
build-mode = "apk"
arch = "all arm64-v8a arm-v7a x86_64"
pkg-name = "com.microsoft.office.excel"
uptodown-dlurl = "https://microsoft-excel-preview.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/microsoft-corporation/excel/"
dpi = "nodpi anydpi auto"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.microsoft.office.excel"
patches-source = "rushiranpise/morphe-patches"



[duolingo-morphe-rushiranpise]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "duolingo"
rv-brand = "morphe-rushiranpise"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.duolingo"
build-mode = "apk"
arch = "all arm64-v8a arm-v7a"
pkg-name = "com.duolingo"
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/duolingo-duolingo"
dpi = "nodpi anydpi auto"
patches-source = "rushiranpise/morphe-patches"



[amazon-india-morphe-rushiranpise]
enabled = true
app-name = "amazon-india"
rv-brand = "morphe-rushiranpise"
build-mode = "apk"
pkg-name = "in.amazon.mShop.android.shopping"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://amazon-india.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-india-shop-pay"
dpi = "nodpi anydpi auto"
patches-source = "rushiranpise/morphe-patches"
included-patches = "'Dark Mode' 'Open Links in Browser'"
excluded-patches = "'Hide Rufus Tab'"
custom-microg-patches = "'None'"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/in.amazon.mShop.android.shopping"

arch = "all"



[amazon-india-morphe-rushiranpise-exp]
enabled = true
app-name = "amazon-india"
rv-brand = "morphe-rushiranpise-exp"
build-mode = "apk"
pkg-name = "in.amazon.mShop.android.shopping"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://amazon-india.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-india-shop-pay"
dpi = "nodpi anydpi auto"
patches-source = "rushiranpise/morphe-patches"
included-patches = "'Dark Mode' 'Open Links in Browser'"
excluded-patches = "'Hide Rufus Tab'"
custom-microg-patches = "'None'"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/in.amazon.mShop.android.shopping"
version = "latest"

arch = "all"



[amazon-shopping-morphe-rushiranpise]
enabled = true
app-name = "amazon-shopping"
rv-brand = "morphe-rushiranpise"
build-mode = "apk"
pkg-name = "com.amazon.mShop.android.shopping"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://amazon-shopping.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-shopping/"
dpi = "nodpi anydpi auto"
patches-source = "rushiranpise/morphe-patches"
included-patches = "'Dark Mode' 'Open Links in Browser'"
excluded-patches = "'Hide Rufus Tab'"
custom-microg-patches = "'None'"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.amazon.mShop.android.shopping"

arch = "all arm64-v8a arm-v7a"



[amazon-shopping-morphe-rushiranpise-exp]
enabled = true
app-name = "amazon-shopping"
rv-brand = "morphe-rushiranpise-exp"
build-mode = "apk"
pkg-name = "com.amazon.mShop.android.shopping"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://amazon-shopping.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-shopping/"
dpi = "nodpi anydpi auto"
patches-source = "rushiranpise/morphe-patches"
included-patches = "'Dark Mode' 'Open Links in Browser'"
excluded-patches = "'Hide Rufus Tab'"
custom-microg-patches = "'None'"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.amazon.mShop.android.shopping"
version = "latest"

arch = "all arm64-v8a arm-v7a"



[adobe-acrobat-morphe-rushiranpise]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "adobe-acrobat"
rv-brand = "morphe-rushiranpise"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.adobe.reader"
build-mode = "apk"
arch = "all arm64-v8a x86_64"
pkg-name = "com.adobe.reader"
uptodown-dlurl = "https://adobe-reader.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/adobe-acrobat"
dpi = "nodpi anydpi auto"
patches-source = "rushiranpise/morphe-patches"
custom-microg-patches = "'None'"



[adobe-acrobat-morphe-rushiranpise-exp]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "adobe-acrobat"
rv-brand = "morphe-rushiranpise-exp"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.adobe.reader"
version = "latest"
build-mode = "apk"
arch = "all arm64-v8a x86_64"
pkg-name = "com.adobe.reader"
uptodown-dlurl = "https://adobe-reader.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/adobe-acrobat"
dpi = "nodpi anydpi auto"
patches-source = "rushiranpise/morphe-patches"
custom-microg-patches = "'None'"


