# --- Patchset: bholeykabhakt (Part 1/1) ---


enable-module-update = true
patches-version = "absolutelatest"



[speedtest-morphe-xtra]
enabled = true
app-name = "speedtest"
pkg-name = "org.zwanoo.android.speedtest"
rv-brand = "morphe-xtra"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/org.zwanoo.android.speedtest"
build-mode = "apk"
arch = "arm64-v8a arm-v7a x86_64"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://speedtest-net-mobile.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/ookla/speedtest"
dpi = "nodpi anydpi auto"
patches-source = "BholeyKaBhakt/revanced-patches-xtra"



[speedtest-morphe-xtra-exp]
enabled = true
app-name = "speedtest"
pkg-name = "org.zwanoo.android.speedtest"
rv-brand = "morphe-xtra-exp"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/org.zwanoo.android.speedtest"
version = "latest"
build-mode = "apk"
arch = "arm64-v8a arm-v7a x86_64"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://speedtest-net-mobile.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/ookla/speedtest"
dpi = "nodpi anydpi auto"
patches-source = "BholeyKaBhakt/revanced-patches-xtra"

