# --- Patchset: brave (Part 1/2) ---


[brave-stable-morphe-kveld9-arm64-v8a]
enabled = true
app-name = "brave-stable"
rv-brand = "morphe-kveld9"
build-mode = "apk"
arch = "arm64-v8a"
pkg-name = "com.brave.browser"
cli-source = "MorpheApp/morphe-desktop"
patches-source = "kveld9/kveld-morphe-patches"
repo-dlurl = "https://github.com/brave/brave-browser"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.brave.browser"
repo-dlurl-filter = "(BraveMonoarm64|MonoArm64)\\.apk$"
repo-dlurl-release-name-filter = "^Release v"



[brave-stable-morphe-kveld9-arm-v7a]
enabled = true
app-name = "brave-stable"
rv-brand = "morphe-kveld9"
build-mode = "apk"
arch = "arm-v7a"
pkg-name = "com.brave.browser"
cli-source = "MorpheApp/morphe-desktop"
patches-source = "kveld9/kveld-morphe-patches"
repo-dlurl = "https://github.com/brave/brave-browser"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.brave.browser"
repo-dlurl-filter = "(BraveMonoarm|MonoArm)\\.apk$"
repo-dlurl-release-name-filter = "^Release v"



[brave-stable-morphe-kveld9-x86_64]
enabled = true
app-name = "brave-stable"
rv-brand = "morphe-kveld9"
build-mode = "apk"
arch = "x86_64"
pkg-name = "com.brave.browser"
cli-source = "MorpheApp/morphe-desktop"
patches-source = "kveld9/kveld-morphe-patches"
repo-dlurl = "https://github.com/brave/brave-browser"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.brave.browser"
repo-dlurl-filter = "(BraveMonox64|BraveMonoX64|Monox64|MonoX64|[xX]64)\\.apk$"
repo-dlurl-release-name-filter = "^Release v"



[brave-stable-morphe-dh6k-arm64-v8a-exp]
enabled = true
app-name = "brave-stable"
rv-brand = "morphe-dh6k-exp"
build-mode = "apk"
arch = "arm64-v8a"
pkg-name = "com.brave.browser"
cli-source = "MorpheApp/morphe-desktop"
patches-source = "dh6k/morphe-patches"
repo-dlurl = "https://github.com/brave/brave-browser/releases"
repo-dlurl-filter = "(BraveMonoarm64|MonoArm64)\\.apk$"
repo-dlurl-release-name-filter = "^Release v"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.brave.browser"
version = "latest"



[brave-stable-morphe-dh6k-arm-v7a-exp]
enabled = true
app-name = "brave-stable"
rv-brand = "morphe-dh6k-exp"
build-mode = "apk"
arch = "arm-v7a"
pkg-name = "com.brave.browser"
cli-source = "MorpheApp/morphe-desktop"
patches-source = "dh6k/morphe-patches"
repo-dlurl = "https://github.com/brave/brave-browser/releases"
repo-dlurl-filter = "(BraveMonoarm|MonoArm)\\.apk$"
repo-dlurl-release-name-filter = "^Release v"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.brave.browser"
version = "latest"



[brave-stable-morphe-dh6k-x86_64-exp]
enabled = true
app-name = "brave-stable"
rv-brand = "morphe-dh6k-exp"
build-mode = "apk"
arch = "x86_64"
pkg-name = "com.brave.browser"
cli-source = "MorpheApp/morphe-desktop"
patches-source = "dh6k/morphe-patches"
repo-dlurl = "https://github.com/brave/brave-browser/releases"
repo-dlurl-filter = "(BraveMonox64|BraveMonoX64|Monox64|MonoX64|[xX]64)\\.apk$"
repo-dlurl-release-name-filter = "^Release v"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.brave.browser"
version = "latest"


