# --- Patchset: hooman (Part 2/2) ---


[poweramp-morphe-hooman]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "poweramp"
rv-brand = "morphe-hooman"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.maxmpz.audioplayer"
build-mode = "apk"
arch = "all arm64-v8a"
pkg-name = "com.maxmpz.audioplayer"
uptodown-dlurl = "https://poweramp-music-player.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/max-mp/poweramp"
apkpure-dlurl = "https://apkpure.com/poweramp-music-player-trial-app/com.maxmpz.audioplayer"
apkcombo-dlurl = "https://apkcombo.com/poweramp/com.maxmpz.audioplayer"
dpi = "nodpi anydpi auto"
patches-source = "arandomhooman/hoomans-morphe-patches"



[poweramp-morphe-hooman-exp]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "poweramp"
rv-brand = "morphe-hooman-exp"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.maxmpz.audioplayer"
version = "latest"
build-mode = "apk"
arch = "all arm64-v8a"
pkg-name = "com.maxmpz.audioplayer"
uptodown-dlurl = "https://poweramp-music-player.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/max-mp/poweramp"
apkpure-dlurl = "https://apkpure.com/poweramp-music-player-trial-app/com.maxmpz.audioplayer"
apkcombo-dlurl = "https://apkcombo.com/poweramp/com.maxmpz.audioplayer"
dpi = "nodpi anydpi auto"
patches-source = "arandomhooman/hoomans-morphe-patches"

