# --- Patchset: rushiranpise (Part 3/4) ---


[oxygen-updater-morphe-rushiranpise]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "oxygen-updater"
rv-brand = "morphe-rushiranpise"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.arjanvlek.oxygenupdater"
custom-microg-patches = "'None'"
build-mode = "apk"
pkg-name = "com.arjanvlek.oxygenupdater"
repo-dlurl = "https://github.com/oxygen-updater/os-updater"
patches-source = "rushiranpise/morphe-patches"



[oxygen-updater-morphe-rushiranpise-exp]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "oxygen-updater"
rv-brand = "morphe-rushiranpise-exp"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.arjanvlek.oxygenupdater"
version = "latest"
custom-microg-patches = "'None'"
build-mode = "apk"
pkg-name = "com.arjanvlek.oxygenupdater"
repo-dlurl = "https://github.com/oxygen-updater/os-updater"
patches-source = "rushiranpise/morphe-patches"



[windscribe-vpn-morphe-rushiranpise]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "windscribe-vpn"
rv-brand = "morphe-rushiranpise"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.windscribe.vpn"
custom-microg-patches = "'None'"
build-mode = "apk"
arch = "all"
pkg-name = "com.windscribe.vpn"
uptodown-dlurl = "https://windscribe.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/windscribe/windscribe-vpn"
apkcombo-dlurl = "https://apkcombo.com/windscribe/com.windscribe.vpn"
dpi = "nodpi anydpi auto"
patches-source = "rushiranpise/morphe-patches"



[windscribe-vpn-morphe-rushiranpise-exp]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "windscribe-vpn"
rv-brand = "morphe-rushiranpise-exp"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.windscribe.vpn"
version = "latest"
custom-microg-patches = "'None'"
build-mode = "apk"
arch = "all"
pkg-name = "com.windscribe.vpn"
uptodown-dlurl = "https://windscribe.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/windscribe/windscribe-vpn"
apkcombo-dlurl = "https://apkcombo.com/windscribe/com.windscribe.vpn"
dpi = "nodpi anydpi auto"
patches-source = "rushiranpise/morphe-patches"



[1111-warp-morphe-rushiranpise]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "1111-warp"
rv-brand = "morphe-rushiranpise"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.cloudflare.onedotonedotonedotone"
custom-microg-patches = "'None'"
build-mode = "apk"
arch = "all"
pkg-name = "com.cloudflare.onedotonedotonedotone"
uptodown-dlurl = "https://1-1-1-1.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/cloudflare/1-1-1-1-faster-safer-internet"
dpi = "nodpi anydpi auto"
patches-source = "rushiranpise/morphe-patches"
apkmirror-exampls-url = "https://www.apkmirror.com/apk/cloudflare/1-1-1-1-faster-safer-internet/1-1-1-1-warp-safer-internet-6-38-9-release/"



[1111-warp-morphe-rushiranpise-exp]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "1111-warp"
rv-brand = "morphe-rushiranpise-exp"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.cloudflare.onedotonedotonedotone"
version = "latest"
custom-microg-patches = "'None'"
build-mode = "apk"
arch = "all"
pkg-name = "com.cloudflare.onedotonedotonedotone"
uptodown-dlurl = "https://1-1-1-1.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/cloudflare/1-1-1-1-faster-safer-internet"
dpi = "nodpi anydpi auto"
patches-source = "rushiranpise/morphe-patches"
apkmirror-exampls-url = "https://www.apkmirror.com/apk/cloudflare/1-1-1-1-faster-safer-internet/1-1-1-1-warp-safer-internet-6-38-9-release/"


