# --- Patchset: rushiranpise (Part 1/4) ---


enable-module-update = true
patches-version = "absolutelatest"


[microsoft-word-morphe-rushiranpise]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "microsoft-word"
rv-brand = "morphe-rushiranpise"
custom-microg-patches = "'None'"
build-mode = "apk"
arch = "all arm64-v8a arm-v7a x86_64"
pkg-name = "com.microsoft.office.word"
uptodown-dlurl = "https://microsoft-word-preview.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/microsoft-corporation/word/"
dpi = "nodpi anydpi auto"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.microsoft.office.word"
patches-source = "rushiranpise/morphe-patches"



[microsoft-excel-morphe-rushiranpise]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "microsoft-excel"
rv-brand = "morphe-rushiranpise"
custom-microg-patches = "'None'"
build-mode = "apk"
arch = "all arm64-v8a arm-v7a x86_64"
pkg-name = "com.microsoft.office.excel"
uptodown-dlurl = "https://microsoft-excel-preview.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/microsoft-corporation/excel/"
dpi = "nodpi anydpi auto"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.microsoft.office.excel"
patches-source = "rushiranpise/morphe-patches"



[duolingo-morphe-rushiranpise]
enabled = true
cli-source = "MorpheApp/morphe-desktop"
app-name = "duolingo"
rv-brand = "morphe-rushiranpise"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/com.duolingo"
build-mode = "apk"
arch = "all arm64-v8a arm-v7a"
pkg-name = "com.duolingo"
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/duolingo-duolingo"
dpi = "nodpi anydpi auto"
patches-source = "rushiranpise/morphe-patches"



[amazon-india-morphe-rushiranpise]
enabled = true
app-name = "amazon-india"
rv-brand = "morphe-rushiranpise"
build-mode = "apk"
pkg-name = "in.amazon.mShop.android.shopping"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://amazon-india.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-india-shop-pay"
dpi = "nodpi anydpi auto"
patches-source = "rushiranpise/morphe-patches"
included-patches = "'Dark Mode' 'Open Links in Browser'"
excluded-patches = "'Hide Rufus Tab'"
custom-microg-patches = "'None'"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/in.amazon.mShop.android.shopping"

arch = "all"



[amazon-india-morphe-rushiranpise-exp]
enabled = true
app-name = "amazon-india"
rv-brand = "morphe-rushiranpise-exp"
build-mode = "apk"
pkg-name = "in.amazon.mShop.android.shopping"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://amazon-india.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-india-shop-pay"
dpi = "nodpi anydpi auto"
patches-source = "rushiranpise/morphe-patches"
included-patches = "'Dark Mode' 'Open Links in Browser'"
excluded-patches = "'Hide Rufus Tab'"
custom-microg-patches = "'None'"
github-dlurl = "https://github.com/sharath-5br2r-apps/apks-dump/releases/tag/in.amazon.mShop.android.shopping"
version = "latest"

arch = "all"


