[imdb-morphe]
enabled = true
app-name = "imdb"
rv-brand = "morphe"
build-mode = "apk"
arch = "all"
patches-source = "jkennethcarino/adobo"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://imdb-cine-tv.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/imdb/imdb-imdb"
dpi = "nodpi anydpi auto"
# archive-dlurl = ""

[gboard-morphe-adobo]
enabled = true
app-name = "gboard"
rv-brand = "morphe-adobo"
build-mode = "both"
arch = "arm64-v8a"
patches-source = "jkennethcarino/adobo"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://gboard-go.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/gboard"
dpi = "nodpi anydpi auto"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.inputmethod.latin"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.google.android.inputmethod.latin"

