[disneyplus-morphe-androidtv]
enabled = true 
pkg-name = "com.disney.disneyplus"
app-name = "disneyplus"
rv-brand = "morphe-androidtv"
build-mode = "apk"
arch = "all"
patches-source = "ajstrick81/morphe-androidtv-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/disney/disney-android-tv"

[prime-video-morphe-androidtv]
enabled = true 
pkg-name = "com.amazon.amazonvideo.livingroom"
app-name = "prime-video"
rv-brand = "morphe-androidtv"
build-mode = "apk"
arch = "arm-v7a"
included-patches = "'Clone Prime Video'"
patches-source = "ajstrick81/morphe-androidtv-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi 320dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/prime-video-android-tv-android-tv"

[hbomax-morphe-androidtv]
enabled = true 
pkg-name = "com.wbd.hbomax"
app-name = "hbomax"
rv-brand = "morphe-androidtv"
build-mode = "apk"
arch = "all"
patches-source = "ajstrick81/morphe-androidtv-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/warnermedia-direct-llc/hbo-max-stream-movies-tv-android-tv"

[peacock-morphe-androidtv]
enabled = true 
pkg-name = "com.peacocktv.peacockandroid"
app-name = "peacock"
rv-brand = "morphe-androidtv"
build-mode = "apk"
arch = "all"
patches-source = "ajstrick81/morphe-androidtv-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/peacock-tv-llc/peacock-tv-android-tv"
# apkpure-dlurl = "https://apkpure.com/peacock-tv-stream-tv-movies/com.peacocktv.peacockandroid"
apkcombo-dlurl = "https://apkcombo.com/peacock-tv/com.peacocktv.peacockandroid"

[tubi-morphe-androidtv]
enabled = true 
pkg-name = "com.tubitv"
app-name = "tubi"
rv-brand = "morphe-androidtv"
build-mode = "apk"
arch = "all"
patches-source = "ajstrick81/morphe-androidtv-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tubi-tv/tubi-free-movies-live-tv-android-tv"

[vix-morphe-androidtv]
enabled = true 
pkg-name = "com.univision.prendetv"
app-name = "vix"
rv-brand = "morphe-androidtv"
build-mode = "apk"
arch = "all"
patches-source = "ajstrick81/morphe-androidtv-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/univision-communications-inc/vix-cine-y-tv-en-espanol-android-tv"

[plutotv-morphe-androidtv]
enabled = true 
pkg-name = "tv.pluto.android"
app-name = "plutotv"
rv-brand = "morphe-androidtv"
build-mode = "apk"
arch = "all"
patches-source = "ajstrick81/morphe-androidtv-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pluto-inc/pluto-tv-android-tv"
uptodown-dlurl = "https://pluto-tv.en.uptodown.com/android"

[netflix-morphe-androidtv]
enabled = true 
pkg-name = "com.netflix.ninja"
app-name = "netflix"
rv-brand = "morphe-androidtv"
build-mode = "apk"
arch = "arm-v7a"
patches-source = "ajstrick81/morphe-androidtv-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/netflix-inc/netflix-android-tv"
uptodown-dlurl = "https://netflix-inc-netflix.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/netflix-android-tv-app/com.netflix.ninja"
apkcombo-dlurl = "https://apkcombo.com/netflix-tv/com.netflix.ninja"
