[automate-morphe]
enabled = true
pkg-name = "com.llamalab.automate"
app-name = "automate"
rv-brand = "morphe"
build-mode = "both"
arch = "both"
patches-source = "BholeyKaBhakt/revanced-patches-xtra"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://automate-beta.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/llamalab/automate-llamalab"
dpi = "nodpi anydpi auto"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.llamalab.automate"

[speedtest-morphe]
enabled = true
pkg-name = "org.zwanoo.android.speedtest"
app-name = "speedtest"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "BholeyKaBhakt/revanced-patches-xtra"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://speedtest-net-mobile.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/ookla/speedtest"
dpi = "nodpi anydpi auto"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/org.zwanoo.android.speedtest"

[autosync-morphe]
enabled = true
pkg-name = "com.ttxapps.autosync"
app-name = "autosync"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "BholeyKaBhakt/revanced-patches-xtra"
# patcher-args = "--continue-on-error"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://autosync.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/metactrl/autosync-universal-cloud-sync-and-backup"
dpi = "nodpi anydpi auto"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.ttxapps.autosync"

[inshorts-morphe]
enabled = true
pkg-name = "com.camerasideas.instashot"
app-name = "inshorts"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "BholeyKaBhakt/revanced-patches-xtra"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://inshorts.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/inshorts-formerly-news-in-shorts/inshorts-news-in-60-words-2"
dpi = "nodpi anydpi auto"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.camerasideas.instashot"

[vpnify-morphe]
enabled = true
pkg-name = "com.vpn.free.hotspot.secure.vpnify"
app-name = "vpnify"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "BholeyKaBhakt/revanced-patches-xtra"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/vpnify/vpnify-unlimited-vpn-proxy"
# uptodown-dlurl = "https://vpnify.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/vpnify-unlimited-vpn-proxy/com.vpn.free.hotspot.secure.vpnify"
apkcombo-dlurl = "https://apkcombo.com/vpnify/com.vpn.free.hotspot.secure.vpnify"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.vpn.free.hotspot.secure.vpnify"

[backdrops-morphe]
enabled = true
pkg-name = "com.backdrops.wallpapers"
app-name = "backdrops"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "BholeyKaBhakt/revanced-patches-xtra"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://backdrops.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/backdrops/backdrops-wallpapers"
dpi = "nodpi anydpi auto"
apkpure-dlurl = "https://apkpure.com/backdrops-wallpapers/com.backdrops.wallpapers"
apkcombo-dlurl = "https://apkcombo.com/backdrops-wallpapers/com.backdrops.wallpapers"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.backdrops.wallpapers"