patches-source = "brosssh/morphe-patches"
brand = "brosssh"

[komoot-brosssh]
enabled = true
pkg-name = "de.komoot.android"
app-name = "Komoot"
apkmirror-dlurl = "https://www.apkmirror.com/apk/komoot-gmbh/komoot-cycling-hiking-mountain-biking-maps"
uptodown-dlurl = "https://komoot.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/komoot-hike-bike-run/de.komoot.android"

[Instagram-brosssh]
enabled = true
pkg-name = "com.instagram.android"
app-name = "Instagram"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/geologically/apks/com.instagram.android"

[Instagram-brosssh-Clone]
enabled = true
pkg-name = "com.instagram.android"
app-name = "Instagram"
variant = "Clone"
included-patches = "'Clone'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/geologically/apks/com.instagram.android"
