[SwiftBackup-byehi98]
enabled = true
pkg-name = "org.swiftapps.swiftbackup"
app-name = "Swift Backup"
patches-source = "byehi98/okish-morphe-patches"
brand = "byehi98"
uptodown-dlurl = "https://swift-backup.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/swiftapps-org/swift-backup"
apkpure-dlurl = "https://apkpure.com/swift-backup/org.swiftapps.swiftbackup"
apkcombo-dlurl = "https://apkcombo.com/swift-backup/org.swiftapps.swiftbackup"