[google-news-morphe]
enabled = true
pkg-name = "com.google.android.apps.magazines"
app-name = "google-news"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "docbt/patched-up"
# patcher-args = "--continue-on-error"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://google-play-newsstand.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-news/"
dpi = "nodpi anydpi auto"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.google.android.apps.magazines"

[trakt-morphe]
enabled = true
pkg-name = "tv.trakt.trakt"
app-name = "trakt"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "IMXEren/mix-patches"
patches-source-host = "gitlab"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://trakt.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/trakt/trakt"
dpi = "nodpi anydpi auto"
# archive-dlurl = ""
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/tv.trakt.trakt"

[komoot-morphe]
enabled = true
pkg-name = "de.komoot.android"
app-name = "komoot"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "brosssh/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/komoot-gmbh/komoot-cycling-hiking-mountain-biking-maps"
uptodown-dlurl = "https://komoot.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/komoot-hike-bike-run/de.komoot.android"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/de.komoot.android"

[discord-xposed]
enabled = true
pkg-name = "com.discord"
app-name = "discord"
rv-brand = "xposed"
build-mode = "apk"
arch = "both"
patches-source = "revenge-mod/revenge-xposed"
cli-source = "7723mod/NPatch"
patcher-args = "-l 0"
dpi = "nodpi anydpi auto"
# uptodown-dlurl = "https://discord-chat-for-gamers.en.uptodown.com/android"
apkcombo-dlurl = "https://apkcombo.com/discord/com.discord"
apkmirror-dlurl = "https://www.apkmirror.com/apk/discord/discord-chat-for-gamers"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.discord"

[microsoft-edge-morphe]
enabled = true
pkg-name = "com.microsoft.emmx"
app-name = "microsoft-edge"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "quantavil/edge-morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://microsoft-edge.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/microsoft-corporation/microsoft-edge"
dpi = "nodpi anydpi auto"
# archive-dlurl = ""
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.microsoft.emmx"

[kinestop-morphe]
enabled = true
pkg-name = "com.urbandroid.kinestop"
app-name = "kinestop"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "shaun-the-sheep-patches/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
apkmirror-dlurl = "https://www.apkmirror.com/apk/urbandroid-team/kinestop-car-sickness-aid"
dpi = "nodpi anydpi auto"
apkpure-dlurl = "https://apkpure.com/kinestop-car-sickness-aid/com.urbandroid.kinestop"
apkcombo-dlurl = "https://apkcombo.com/kinestop-car-sickness-aid/com.urbandroid.kinestop"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.urbandroid.kinestop"

[facebook-morphe]
enabled = true
pkg-name = "com.facebook.katana"
app-name = "facebook"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "MeridianFresco/morphe-meta-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://facebook.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.facebook.katana"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.facebook.katana"

[threads-morphe]
enabled = true
pkg-name = "com.instagram.barcelona"
app-name = "threads"
rv-brand = "morphe"
patch-folder = "threads"
build-mode = "apk"
arch = "both"
patches-source = "durgesh0505/chiggi_morphe_patches"
excluded-patches = "'Change app name' 'Change package name'"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://threads.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/threads-an-instagram-app"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.instagram.barcelona"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.instagram.barcelona"

[byair-morphe]
enabled = true
pkg-name = "com.byairapp.android"
app-name = "byair"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "franticg33k/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
apkmirror-dlurl = "https://www.apkmirror.com/apk/byairapp-s-l/byair-flight-tracker-status"
dpi = "nodpi anydpi auto"
apkpure-dlurl = "https://apkpure.com/byair-flight-tracker-status/com.byairapp.android"
apkcombo-dlurl = "https://apkcombo.com/byair-flight-tracker-status/com.byairapp.android"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.byairapp.android"



