[brave-browser-morphe-beta]
enabled = true
pkg-name = "com.brave.browser_beta"
app-name = "brave-browser"
rv-brand = "morphe-beta"
build-mode = "apk"
arch = "both"
patches-source = "dh6k/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://brave-browser-beta.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/brave-software/brave-browser-beta"
dpi = "nodpi anydpi auto"
apkpure-dlurl = "https://apkpure.com/brave-browser-beta/com.brave.browser_beta"
apkcombo-dlurl = "https://apkcombo.com/brave-beta/com.brave.browser_beta"
github-dlurl = "https://github.com/brave/brave-browser"
github-regex = 'arm64-v8a: BraveMonoarm64\.apk | arm-v7a: BraveMonoarm\.apk'

[brave-browser-morphe-nightly]
enabled = true
pkg-name = "com.brave.browser_nightly"
app-name = "brave-browser"
rv-brand = "morphe-nightly"
build-mode = "apk"
arch = "both"
patches-source = "dh6k/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://brave-browser-nightly.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/brave-software/brave-browser-nightly"
dpi = "nodpi anydpi auto"
apkpure-dlurl = "https://apkpure.com/brave-nightly/com.brave.browser_nightly"
apkcombo-dlurl = "https://apkcombo.com/brave-nightly/com.brave.browser_nightly"
github-dlurl = "https://github.com/brave/brave-browser"
github-regex = 'arm64-v8a: BraveMonoarm64\.apk | arm-v7a: BraveMonoarm\.apk'

[titanium-browser-morphe]
enabled = true
pkg-name = "io.github.jqssun.helium"
app-name = "titanium-browser"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "dh6k/morphe-patches"
included-patches = "'Keep Helium Child Processes Alive'"
cli-source = "MorpheApp/morphe-desktop"
# dpi = "nodpi anydpi auto"
apkpure-dlurl = "https://apkpure.com/helium-browser/io.github.jqssun.helium"
apkcombo-dlurl = "https://apkcombo.com/titanium-browser/io.github.jqssun.helium"
