[brave-browser-morphe-beta]
enabled = true
pkg-name = "com.brave.browser_beta"
app-name = "brave-browser"
rv-brand = "morphe-beta"
build-mode = "apk"
arch = "both"
patches-source = "dh6k/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://brave-browser-beta.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/brave-software/brave-browser-beta"
dpi = "nodpi anydpi auto"
apkpure-dlurl = "https://apkpure.com/brave-browser-beta/com.brave.browser_beta"
apkcombo-dlurl = "https://apkcombo.com/brave-beta/com.brave.browser_beta"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.brave.browser_beta"

[brave-browser-morphe-nightly]
enabled = true
pkg-name = "com.brave.browser_nightly"
app-name = "brave-browser"
rv-brand = "morphe-nightly"
build-mode = "apk"
arch = "both"
patches-source = "dh6k/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://brave-browser-nightly.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/brave-software/brave-browser-nightly"
dpi = "nodpi anydpi auto"
apkpure-dlurl = "https://apkpure.com/brave-nightly/com.brave.browser_nightly"
apkcombo-dlurl = "https://apkcombo.com/brave-nightly/com.brave.browser_nightly"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.brave.browser_nightly"