patches-source = "hoo-dles/morphe-patches"
brand = "hoodles"

[SoundCloud-hoodles]
enabled = true
pkg-name = "com.soundcloud.android"
app-name = "SoundCloud"
included-patches = "'AMOLED dark theme'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/soundcloud/soundcloud-soundcloud"
uptodown-dlurl = "https://soundcloud.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/sound-cloud-android-app/com.soundcloud.android"
apkcombo-dlurl = "https://apkcombo.com/soundcloud/com.soundcloud.android"

[Duolingo-hoodles]
enabled = true
pkg-name = "com.duolingo"
app-name = "Duolingo"
apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/duolingo-duolingo"
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/duolingo-learn-languages/com.duolingo"
apkcombo-dlurl = "https://apkcombo.com/duolingo/com.duolingo"

[WPSOffice-hoodles]
enabled = true
pkg-name = "cn.wps.moffice_eng"
app-name = "WPS Office"
apkmirror-dlurl = "https://www.apkmirror.com/apk/wps-software-pte-ltd/wps-office-pdf"
uptodown-dlurl = "https://wps-office.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/wps-office-pdf-word-excel-ppt/cn.wps.moffice_eng"
apkcombo-dlurl = "https://apkcombo.com/wps-office/cn.wps.moffice_eng"

[Wallcraft-hoodles]
enabled = true
pkg-name = "com.wallpaperscraft.wallpaper"
app-name = "Wallcraft"
apkmirror-dlurl = "https://www.apkmirror.com/apk/nebuchadnezzar-doo/wallpapers-hd-4k-backgrounds"
uptodown-dlurl = "https://wallpaperscraft.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/wallpaper-4k-hd-%E2%80%93-wallcraft/com.wallpaperscraft.wallpaper"
apkcombo-dlurl = "https://apkcombo.com/wallpaper-4k-hd-wallcraft/com.wallpaperscraft.wallpaper"

[SolidExplorer-hoodles]
enabled = true
pkg-name = "pl.solidexplorer2"
app-name = "Solid Explorer"
apkmirror-dlurl = "https://www.apkmirror.com/apk/lmicp/solid-explorer-file-manager"
uptodown-dlurl = "https://solid-explorer-file-manager.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/solid-explorer-file-manager/pl.solidexplorer2"
apkcombo-dlurl = "https://apkcombo.com/solid-explorer/pl.solidexplorer2"

[IconPacker-hoodles]
enabled = true
pkg-name = "cn.ommiao.iconpacker"
app-name = "Icon Packer"
apkpure-dlurl = "https://apkpure.com/icon-packer/cn.ommiao.iconpacker"
apkcombo-dlurl = "https://apkcombo.com/icon-packer/cn.ommiao.iconpacker"
archive-dlurl = "https://archive.org/download/geologically/apks/cn.ommiao.iconpacker"

[PodcastAddict-hoodles]
enabled = true
pkg-name = "com.bambuna.podcastaddict"
app-name = "Podcast Addict"
apkmirror-dlurl = "https://www.apkmirror.com/apk/xavier-guillemane/podcast-addict"
uptodown-dlurl = "https://podcast-addict.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/podcast-addict-app/com.bambuna.podcastaddict"
apkcombo-dlurl = "https://apkcombo.com/podcast-addict-podcast-player/com.bambuna.podcastaddict"
archive-dlurl = "https://archive.org/download/geologically/apks/com.bambuna.podcastaddict"

[SmartLauncher6-hoodles]
enabled = true
pkg-name = "ginlemon.flowerfree"
app-name = "Smart Launcher 6"
patch-folder = "smartlauncher"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/smart-launcher"
uptodown-dlurl = "https://smart-launcher.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/smart-launcher-6/ginlemon.flowerfree"
apkcombo-dlurl = "https://apkcombo.com/smart-launcher-6-%E2%80%A7-home-screen/ginlemon.flowerfree"
archive-dlurl = "https://archive.org/download/geologically/apks/ginlemon.flowerfree"

[MerriamWebsterDictionary-hoodles]
enabled = true
pkg-name = "com.merriamwebster"
app-name = "Merriam Webster Dictionary"
patch-folder = "webster"
apkmirror-dlurl = "https://www.apkmirror.com/apk/merriam-webster-inc/dictionary-merriam-webster"
apkpure-dlurl = "https://apkpure.com/dictionary-merriam-webster/com.merriamwebster"
apkcombo-dlurl = "https://apkcombo.com/dictionary-merriam-webster/com.merriamwebster"
uptodown-dlurl = "https://merriam-webster-dictionary.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/geologically/apks/com.merriamwebster"

[Pandora-hoodles]
enabled = true
pkg-name = "com.pandora.android"
app-name = "Pandora"
apkmirror-dlurl = "https://www.apkmirror.com/apk/pandora/pandora-music-podcasts"
apkcombo-dlurl = "https://apkcombo.com/pandora/com.pandora.android"
archive-dlurl = "https://archive.org/download/geologically/apks/com.pandora.android"

[XRecorder-hoodles]
enabled = true
pkg-name = "videoeditor.videorecorder.screenrecorder"
app-name = "XRecorder"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/inshot-inc-2/screen-recorder-video-recorder-xrecorder"
apkpure-dlurl = "https://apkpure.com/screen-recorder-xrecorder-app/videoeditor.videorecorder.screenrecorder"
apkcombo-dlurl = "https://apkcombo.com/xrecorder/videoeditor.videorecorder.screenrecorder"
uptodown-dlurl = "https://videoeditor-videorecorder-screenrecorder.en.uptodown.com/android"

[AdGuard-hoodles]
enabled = true
pkg-name = "com.adguard.android"
app-name = "AdGuard"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adguard-software-limited/adguard"
uptodown-dlurl = "https://adguard-for-android.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/adguard/com.adguard.android"

[NovaLauncher-hoodles]
enabled = true
pkg-name = "com.teslacoilsw.launcher"
app-name = "Nova Launcher"
patch-folder = "nova"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instabridge-sweden-ab/nova-launcher"
uptodown-dlurl = "https://nova-launcher.en.uptodown.com/android"
apkcombo-dlurl = "https://apkcombo.com/nova-launcher-home-screen/com.teslacoilsw.launcher"
apkpure-dlurl = "https://apkpure.com/nova-launcher-home-screen/com.teslacoilsw.launcher"
archive-dlurl = "https://archive.org/download/geologically/apks/com.teslacoilsw.launcher"

[Ventusky-hoodles]
enabled = true
pkg-name = "cz.ackee.ventusky"
app-name = "Ventusky"
apkmirror-dlurl = "https://www.apkmirror.com/apk/ventusky/ventusky-weather-maps-radar"
uptodown-dlurl = "https://ventusky-weather-maps-and-radar.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/ventusky-weather-radar/cz.ackee.ventusky"
apkcombo-dlurl = "https://apkcombo.com/ventusky/cz.ackee.ventusky"
archive-dlurl = "https://archive.org/download/geologically/apks/cz.ackee.ventusky"

[CamScanner-hoodles]
enabled = true
pkg-name = "com.intsig.camscanner"
app-name = "CamScanner"
apkmirror-dlurl = "https://www.apkmirror.com/apk/intsig-pte/camscanner-phone-pdf-creator"
uptodown-dlurl = "https://camscanner-pdf-creator.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/camscanner-scanner-pdf-maker/com.intsig.camscanner"
apkcombo-dlurl = "https://apkcombo.com/camscanner/com.intsig.camscanner"

[NiagaraLauncher-hoodles]
enabled = true
pkg-name = "bitpit.launcher"
app-name = "Niagara Launcher"
patch-folder = "niagara"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/mellowdrop-studio/niagara-launcher-%f0%9f%94%b9-fresh-clean"
uptodown-dlurl = "https://niagara-launcher.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/niagara-launcher-%E2%80%A7-fresh-clean/bitpit.launcher"
apkcombo-dlurl = "https://apkcombo.com/niagara-launcher/bitpit.launcher"

[GitHub-hoodles]
enabled = true
pkg-name = "com.github.android"
app-name = "GitHub"
included-patches = "'AMOLED dark theme'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/github/github-2"
uptodown-dlurl = "https://github-android.en.uptodown.com/android"

[ProtonVPN-hoodles]
enabled = true
pkg-name = "ch.protonvpn.android"
app-name = "Proton VPN"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/geologically/apks/ch.protonvpn.android"

[HelloChinese-hoodles]
enabled = true
pkg-name = "com.hellochinese"
app-name = "HelloChinese"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/hellochinese-learn-chinese-mandarin/hellochinese-learn-chinese"
uptodown-dlurl = "https://hellochinese.en.uptodown.com/android"

[MyFitnessPal-hoodles]
enabled = true
pkg-name = "com.myfitnesspal.android"
app-name = "MyFitnessPal"
apkmirror-dlurl = "https://www.apkmirror.com/apk/myfitnesspal-inc/calorie-counter-myfitnesspal"
uptodown-dlurl = "https://calorie-counter-myfitnesspal.en.uptodown.com/android"

[PrimeVideo-hoodles]
enabled = true
pkg-name = "com.amazon.avod.thirdpartyclient"
app-name = "Prime Video"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video"
uptodown-dlurl = "https://amazon-video.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/prime-video-android-tv/com.amazon.amazonvideo.livingroom"
apkcombo-dlurl = "https://apkcombo.com/prime-video/com.amazon.avod.thirdpartyclient"

[Goodreads-hoodles]
enabled = true
pkg-name = "com.goodreads"
app-name = "Goodreads"
apkmirror-dlurl = "https://www.apkmirror.com/apk/goodreads/goodreads"
uptodown-dlurl = "https://goodreads.en.uptodown.com/android"

[AdobeLightroom-hoodles]
enabled = true
pkg-name = "com.adobe.lrmobile"
app-name = "Adobe Lightroom"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
uptodown-dlurl = "https://adobe-lightroom-mobile.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/geologically/apks/com.adobe.lrmobile"
