[rumble-morphe]
enabled = true
pkg-name = "com.rumble.battles"
app-name = "rumble"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "arandomhooman/hoomans-morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://rumble.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/rumble-inc/rumble"
dpi = "nodpi anydpi auto"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.rumble.battles"

[twitch-morphe]
enabled = true
pkg-name = "tv.twitch.android.app"
app-name = "twitch"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "arandomhooman/hoomans-morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/tv.twitch.android.app"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/tv.twitch.android.app"

[battery-guru-morphe]
enabled = true
pkg-name = "com.paget96.batteryguru"
app-name = "battery-guru"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "arandomhooman/hoomans-morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://battery-guru.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/paget96/battery-guru-health-saver/"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/tv.twitch.android.app"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.paget96.batteryguru"

[money-manager-morphe]
enabled = true
pkg-name = "com.realbyteapps.moneymanagerfree"
app-name = "money-manager"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "arandomhooman/hoomans-morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://money-manager.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/realbyte-inc/money-manager-expense-budget"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/tv.twitch.android.app"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.realbyteapps.moneymanagerfree"

[poweramp-morphe]
enabled = true
pkg-name = "com.maxmpz.audioplayer"
app-name = "poweramp"
rv-brand = "morphe"
build-mode = "apk"
arch = "all"
patches-source = "arandomhooman/hoomans-morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
uptodown-dlurl = "https://poweramp-music-player.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/max-mp/poweramp"
apkpure-dlurl = "https://apkpure.com/poweramp-music-player-trial-app/com.maxmpz.audioplayer"
apkcombo-dlurl = "https://apkcombo.com/poweramp/com.maxmpz.audioplayer"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.maxmpz.audioplayer"

[at4k-launcher-morphe]
enabled = true 
pkg-name = "com.overdevs.at4k"
app-name = "at4k-launcher"
rv-brand = "morphe"
build-mode = "apk"
arch = "all"
patches-source = "arandomhooman/hoomans-morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/cute-little-apps/at4k-launcher-android-tv"
apkpure-dlurl = "https://apkpure.com/at4k-launcher/com.overdevs.at4k"
# apkcombo-dlurl = "https://apkcombo.com/at4k-launcher/com.overdevs.at4k"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.overdevs.at4k"

[snorelab-morphe]
enabled = true
pkg-name = "com.snorelab.app"
app-name = "snorelab"
rv-brand = "morphe"
build-mode = "apk"
arch = "all"
patches-source = "arandomhooman/hoomans-morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/reviva-softworks-ltd/snorelab-record-your-snoring"
uptodown-dlurl = "https://snorelab-record-your-snoring.en.uptodown.com/android"

[projectivy-launcher-morphe]
enabled = true 
pkg-name = "com.spocky.projengmenu"
app-name = "projectivy-launcher"
rv-brand = "morphe"
build-mode = "apk"
arch = "all"
patches-source = "arandomhooman/hoomans-morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/spocky/projectivy-launcher-android-tv"
# uptodown-dlurl = "https://projectivy-launcher.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/projectivy-launcher/com.spocky.projengmenu"
apkcombo-dlurl = "https://apkcombo.com/projectivy-launcher/com.spocky.projengmenu/"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.spocky.projengmenu"

[adobe-acrobat-morphe]
enabled = true 
pkg-name = "com.adobe.reader"
app-name = "adobe-acrobat"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "arandomhooman/hoomans-morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/adobe-acrobat"
uptodown-dlurl = "https://adobe-reader.en.uptodown.com/android"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.adobe.reader"

[inshot-morphe]
enabled = true 
pkg-name = "com.camerasideas.instashot"
app-name = "inshot"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "arandomhooman/hoomans-morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/inshot-inc/inshot-video-editor-photo-editor"
uptodown-dlurl = "https://inshot-editor.en.uptodown.com/android"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.camerasideas.instashot"

[todoist-morphe]
enabled = true 
pkg-name = "com.todoist"
app-name = "todoist"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "arandomhooman/hoomans-morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/doist/todoist"
# uptodown-dlurl = "https://todoist.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/todoist-to-do-list-planner/com.todoist"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.todoist"

[tumblr-morphe]
enabled = true
pkg-name = "com.tumblr"
app-name = "tumblr"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "arandomhooman/hoomans-morphe-patches"
uptodown-dlurl = "https://tumblr.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tumblr-inc/tumblr"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.tumblr"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.tumblr"

[google-phone-morphe]
enabled = true
pkg-name = "com.google.android.dialer"
app-name = "google-phone"
rv-brand = "morphe"
build-mode = "both"
arch = "both"
patches-source = "arandomhooman/hoomans-morphe-patches"
uptodown-dlurl = "https://google-phone.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-phone"
dpi = "nodpi anydpi auto"
apkpure-dlurl = "https://apkpure.com/phone-by-google-app/com.google.android.dialer"
apkcombo-dlurl = "https://apkcombo.com/google-phone/com.google.android.dialer"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.dialer"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.google.android.dialer"

