[proton-mail-morphe]
enabled = true
pkg-name = "ch.protonmail.android"
app-name = "proton-mail"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "hxreborn/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://protonmail.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email"
dpi = "nodpi anydpi auto"
apkpure-dlurl = "https://apkpure.com/proton-mail-encrypted-email/ch.protonmail.android"
apkcombo-dlurl = "https://apkcombo.com/proton-mail/ch.protonmail.android"
archive-dlurl = "https://archive.org/download/geologically/apks/ch.protonmail.android"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/ch.protonmail.android"

[showly-morphe]
enabled = true
pkg-name = "com.michaldrabik.showly2"
app-name = "showly"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "hxreborn/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://showly-2-0.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/trakt/showly"
dpi = "nodpi anydpi auto"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.michaldrabik.showly2"

[tiktok-morphe-alt]
enabled = true
pkg-name = "com.zhiliaoapp.musically"
app-name = "tiktok"
rv-brand = "morphe-alt"
build-mode = "apk"
arch = "both"
patches-source = "hxreborn/hxreborn-tiktok-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
dpi = "nodpi anydpi auto"
archive-dlurl = "https://archive.org/download/geologically/apks/com.zhiliaoapp.musically"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.zhiliaoapp.musically"




