patches-source = "hxreborn/morphe-patches"
brand = "hxreborn"

[ProtonMail-hxreborn]
enabled = true
pkg-name = "ch.protonmail.android"
app-name = "Proton Mail"
apkmirror-dlurl = "https://apkmirror.com/apk/proton-technologies-ag/protonmail-encrypted-email"
uptodown-dlurl = "https://protonmail.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/proton-mail-encrypted-email/ch.protonmail.android"
apkcombo-dlurl = "https://apkcombo.com/proton-mail/ch.protonmail.android"
archive-dlurl = "https://archive.org/download/geologically/apks/ch.protonmail.android"

[Showly-hxreborn]
enabled = true
pkg-name = "com.michaldrabik.showly2"
app-name = "Showly"
apkmirror-dlurl = "https://www.apkmirror.com/apk/trakt/showly"
uptodown-dlurl = "https://showly-2-0.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/showly-track-tv-shows-movie/com.michaldrabik.showly2"
apkcombo-dlurl = "https://apkcombo.com/showly-track-shows-movies/com.michaldrabik.showly2"

[TikTok-hxreborn]
enabled = true
pkg-name = "com.zhiliaoapp.musically"
app-name = "TikTok"
patches-source = "hxreborn/hxreborn-tiktok-patches"
patches-version = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/tiktok-app/com.zhiliaoapp.musically"
archive-dlurl = "https://archive.org/download/geologically/apks/com.zhiliaoapp.musically"



