patches-source = "instafel/pc-rel"
cli-source = "instafel/p-rel"
brand = "Instafel"

[Instagram-InstaFel]
enabled = true
pkg-name = "com.instagram.android"
app-name = "Instagram"
included-patches = "'unlock_developer_options' 'remove_snooze_warning' 'remove_ads' 'amoled_theme' 'instafel'"
dpi = "480dpi nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"

[Instagram-InstaFel-Clone]
enabled = true
pkg-name = "com.instagram.android"
app-name = "Instagram"
variant = "Clone"
included-patches = "'unlock_developer_options' 'remove_snooze_warning' 'remove_ads' 'amoled_theme' 'instafel' 'clone'"
dpi = "480dpi nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"




