[calorie-counter-morphe]
enabled = true
pkg-name = "com.fatsecret.android"
app-name = "calorie-counter"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "kondratjev/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://fatsecret-calorie-counter.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/fatsecret/calorie-counter-by-fatsecret/"
dpi = "nodpi anydpi auto"
apkpure-dlurl = "https://apkpure.com/calorie-counter-by-fatsecret/com.fatsecret.android"
apkcombo-dlurl = "https://apkcombo.com/fatsecret/com.fatsecret.android"
# archive-dlurl = ""
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.fatsecret.android"

[soundcloud-morphe-alt]
enabled = true
pkg-name = "com.soundcloud.android"
app-name = "soundcloud"
rv-brand = "morphe-alt"
build-mode = "apk"
arch = "both"
patches-source = "kondratjev/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://soundcloud.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/soundcloud/soundcloud-soundcloud"
dpi = "nodpi anydpi auto"
apkpure-dlurl = "https://apkpure.com/sound-cloud-android-app/com.soundcloud.android"
apkcombo-dlurl = "https://apkcombo.com/soundcloud/com.soundcloud.android"
# archive-dlurl = ""
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.soundcloud.android"