[nuvio-morphe-androidtv]
enabled = true
pkg-name = "com.nuvio.tv"
app-name = "nuvio"
rv-brand = "morphe-androidtv"
build-mode = "apk"
arch = "both"
patches-source = "liongalahad/nuviotv-morphe-patches"
included-patches = "'Allow Importing Subs from Local Storage' 'Library Mode Focus Fix' 'Local Downloads' 'Local Media' 'Mark SDH Subtitles' 'Random Episode' 'Remove SDH Annotations' 'Restore Source Selection'"
excluded-patches = "'Side-by-side installation'"
cli-source = "MorpheApp/morphe-desktop"
github-dlurl = "https://github.com/NuvioMedia/NuvioTV"
github-regex = "app-full-universal-release\\.apk"
