patches-source = "Paresh-Maheshwari/paresh-patches"
patches-source-host = "gitlab"
brand = "Paresh"

[Cricbuzz-Paresh]
enabled = true
pkg-name = "com.cricbuzz.android"
app-name = "Cricbuzz"
apkmirror-dlurl = "https://www.apkmirror.com/apk/cricbuzz-com/cricbuzz-live-cricket-scores-news"
uptodown-dlurl = "https://cricbuzz-cricket-scores-and-news.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/cricbuzz-live-cricket-scores/com.cricbuzz.android"
apkcombo-dlurl = "https://apkcombo.com/cricbuzz/com.cricbuzz.android"

[PlusMessenger-Paresh]
enabled = true
pkg-name = "org.telegram.plus"
app-name = "Plus Messenger"
apkmirror-dlurl = "https://www.apkmirror.com/apk/rafalense/plus-messenger"
uptodown-dlurl = "https://telegram-plus.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/2025-plus-messenger-questions-tool/org.telegram.plus"
apkcombo-dlurl = "https://apkcombo.com/plus-messenger/org.telegram.plus"

[LuminaWallpapers-Paresh]
enabled = true
pkg-name = "com.lumina.wallpapers"
app-name = "Lumina Wallpapers"
uptodown-dlurl = "https://lumina-walls.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/lumina-wallpapers/com.lumina.wallpapers"
apkcombo-dlurl = "https://apkcombo.com/lumina-wallpapers/com.lumina.wallpapers"

[Eyecon-Paresh]
enabled = true
pkg-name = "com.eyecon.global"
app-name = "Eyecon"
apkmirror-dlurl = "https://www.apkmirror.com/apk/eyecon-phone-dialer-contacts/eyecon-caller-id-spam-block"
uptodown-dlurl = "https://eyecon-phone-dialer-and-cont-eyecon.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/eyecon-caller-id-spam-block/com.eyecon.global"
apkcombo-dlurl = "https://apkcombo.com/eyecon/com.eyecon.global"

[TickTick-Paresh]
enabled = true
pkg-name = "com.ticktick.task"
app-name = "TickTick"
apkmirror-dlurl = "https://www.apkmirror.com/apk/ticktick-limited/ticktick-to-do-list-with-reminder-day-planner"
uptodown-dlurl = "https://ticktick.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/ticktick-to-do-list-calendar/com.ticktick.task"
apkcombo-dlurl = "https://apkcombo.com/ticktick/com.ticktick.task"

[SDMaid-Paresh]
enabled = true
pkg-name = "eu.darken.sdmse"
app-name = "SD Maid 2/SE"
apkmirror-dlurl = "https://www.apkmirror.com/apk/darken/sd-maid-2-se-system-cleaner"
uptodown-dlurl = "https://sd-maid-se.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/sd-maid-2-se-system-cleaner/eu.darken.sdmse"
apkcombo-dlurl = "https://apkcombo.com/sd-maid-2-se-system-cleaner/eu.darken.sdmse"

[ProtonVPN-Paresh]
enabled = true
pkg-name = "ch.protonvpn.android"
app-name = "Proton VPN"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/geologically/apks/ch.protonvpn.android"

[Truecaller-Paresh]
enabled = true
pkg-name = "com.truecaller"
app-name = "Truecaller"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/true-software-scandinavia-ab/truecaller-caller-id-block"
uptodown-dlurl = "https://truecaller.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/geologically/apks/com.truecaller"

[Fing-Paresh]
enabled = true
pkg-name = "com.overlook.android.fing"
app-name = "Fing"
apkmirror-dlurl = "https://www.apkmirror.com/apk/fing-limited/fing-network-tools"
uptodown-dlurl = "https://fing-network-tools.en.uptodown.com/android"

[Telegram-Paresh-FOSS]
enabled = true
pkg-name = "org.telegram.messenger.web"
app-name = "Telegram"
variant = "FOSS"
apkmirror-dlurl = "https://www.apkmirror.com/apk/telegram-fz-llc/telegram-web-version"
uptodown-dlurl = "https://telegram.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/telegram-messenger/org.telegram.messenger.web"
apkcombo-dlurl = "https://apkcombo.com/telegram/org.telegram.messenger.web"

[MacroDroid-Paresh]
enabled = true
pkg-name = "com.arlosoft.macrodroid"
app-name = "MacroDroid"
build-mode = "both"
apkmirror-dlurl = "https://www.apkmirror.com/apk/arlosoft/macrodroid-device-automation-2"
uptodown-dlurl = "https://macrodroid.en.uptodown.com/android"


