[adguard-morphe-nightly]
enabled = true
pkg-name = "com.adguard.android"
app-name = "adguard"
rv-brand = "morphe-nightly"
build-mode = "both"
arch = "both"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://adguard-for-android.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adguard-software-limited/adguard"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.adguard.android"

[waze-morphe]
enabled = true
pkg-name = "com.waze"
app-name = "waze"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://waze.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/waze/waze-gps-maps-traffic-alerts-live-navigation"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/tv.twitch.android.app"

[warp-morphe]
enabled = true
pkg-name = "com.cloudflare.onedotonedotonedotone"
app-name = "warp"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://1-1-1-1.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/cloudflare/1-1-1-1-faster-safer-internet"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/tv.twitch.android.app"


[hola-vpn-morphe]
enabled = true
pkg-name = "org.hola.play"
app-name = "hola-vpn"
rv-brand = "morphe"
build-mode = "apk"
arch = "arm64-v8a"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
uptodown-dlurl = "https://holavpn.en.uptodown.com/android"
apkpure-dlurl = "https://apkpure.com/hola-free-vpn-proxy-unblocker/org.hola"
apkcombo-dlurl = "https://apkcombo.com/hola-vpn-fast-free-vpn-proxy/org.hola.play"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/org.hola.play"

[ninja-vpn-morphe]
enabled = true
pkg-name = "app.ninjavpn.android"
app-name = "ninja-vpn"
rv-brand = "morphe"
build-mode = "apk"
arch = "arm64-v8a"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
apkpure-dlurl = "https://apkpure.com/ninja-vpn-fast-secure-vpn/app.ninjavpn.android"
# uptodown-dlurl = "https://ninja-vpn.uptodown.com/android"
apkcombo-dlurl = "https://apkcombo.com/ninja-vpn-fast-secure-vpn/app.ninjavpn.android"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/app.ninjavpn.android"

[windscribe-vpn-morphe]
enabled = true
pkg-name = "com.windscribe.vpn"
app-name = "windscribe-vpn"
rv-brand = "morphe"
build-mode = "apk"
arch = "all"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/windscribe/windscribe-vpn"
uptodown-dlurl = "https://windscribe.uptodown.com/android"
apkcombo-dlurl = "https://apkcombo.com/windscribe/com.windscribe.vpn"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.windscribe.vpn"

[terabox-morphe]
enabled = true
pkg-name = "com.dubox.drive"
app-name = "terabox"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
dpi = "nodpi anydpi auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/flextech-inc/terabox-cloud-storage-cloud-backup-data-backup"
uptodown-dlurl = "https://terabox.en.uptodown.com/android"

[accuweather-morphe]
enabled = true
pkg-name = "com.accuweather.android"
app-name = "accuweather"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://accuweather.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/accuweather/accuweather"
dpi = "nodpi anydpi auto"
# archive-dlurl = ""
apkcombo-dlurl = "https://apkcombo.com/accuweather/com.accuweather.android"
apkpure-dlurl = "https://apkpure.com/accuweather-weather-radar/com.accuweather.android"

[the-weather-channel-morphe]
enabled = true
pkg-name = "com.weather.Weather"
app-name = "the-weather-channel"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://the-weather-channel.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/the-weather-channel/the-weather-channel-local-forecast-weather-maps"
dpi = "nodpi anydpi auto"
# archive-dlurl = ""
apkcombo-dlurl = "https://apkcombo.com/the-weather-channel/com.weather.Weather"
apkpure-dlurl = "https://apkpure.com/the-weather-channel-radar/com.weather.Weather"

[beta-maniac-morphe]
enabled = true
pkg-name = "it.mirko.beta"
app-name = "beta-maniac"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://beta-maniac.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/mirko-dimartino/beta-maniac-life-of-a-beta-tester-2"
dpi = "nodpi anydpi auto"
# archive-dlurl = ""

[google-photos-morphe-alt]
enabled = true
pkg-name = "com.google.android.apps.photos"
app-name = "google-photos"
rv-brand = "morphe-alt"
build-mode = "apk"
arch = "both"
patches-source = "rushiranpise/morphe-patches"
included-patches = "'AMOLED dark theme' 'Change package name' 'Enable DCIM folders backup control' 'Fix DCIM folder classification'"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"
dpi = "nodpi anydpi auto"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.photos"

[moviebox-morphe]
enabled = true
pkg-name = "com.community.oneroom"
app-name = "moviebox"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
uptodown-dlurl = "https://com-community-oneroom.en.uptodown.com/android"
# apkmirror-dlurl = ""
# dpi = "nodpi anydpi auto"
# archive-dlurl = ""
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.community.oneroom"

[moviebox-morphe-androidtv]
enabled = true
pkg-name = "com.community.mbox.tv"
app-name = "moviebox"
rv-brand = "morphe-androidtv"
build-mode = "apk"
arch = "both"
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-desktop"
# uptodown-dlurl = ""
# apkmirror-dlurl = ""
# dpi = "nodpi anydpi auto"
# archive-dlurl = ""
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.community.mbox.tv"




