patches-version="latest"
[zalith-launcher-2-plus-viamorphe-codm]
enabled = true
app-name = "zalith-launcher-2-plus"
rv-brand = "viamorphe-codm"
build-mode = "apk"
cli-source = "MorpheApp/morphe-desktop"
github2-dlurl = "https://github.com/Star1xr/ZalithLauncher2Plus"
github2-pkg-name = "com.movtery.zalithlauncher.v2"
patches-source = "MorpheApp/morphe-patches"
patcher-args = "-OpackageName='com.activision.callofduty.shooter'"
included-patches = "'Change Package Name'"
