name: Probe Permissions
on:
  workflow_dispatch:
permissions: write-all
jobs:
  probe:
    uses: ./.github/workflows/build.yml
    with:
      config_file: ".github/configs/config.beta.updated.json"
    secrets: inherit
