name: Update Website

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: website
  cancel-in-progress: true

jobs:
  dispatch_update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Dispatch Website Cache Update
        env:
          PAT_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          WEBSITE_REPO: ${{ secrets.WEBSITE_REPO }}
        run: |
          if [ -n "${WEBSITE_REPO:-}" ] && [ -n "${PAT_TOKEN:-}" ]; then
            curl -X POST "https://api.github.com/repos/${WEBSITE_REPO}/dispatches" \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token $PAT_TOKEN" \
              -d '{"event_type": "update-catalog-cache"}'
          else
            echo "WEBSITE_REPO or PERSONAL_ACCESS_TOKEN is not present. Skipping website update."
          fi
